# yamllint disable rule:key-ordering
---
title: 'Admin'
views:
  - path: 'hass'
    title: 'Home Assistant'
    badges:
      - 'binary_sensor.remote_ui'
      - 'binary_sensor.snapshots_stale'
      - 'sensor.snapshot_backup'
  - path: 'host'
    title: 'Host'
    badges:
      - 'sensor.disk_free'
      - 'sensor.disk_use'
      - 'sensor.disk_use_percent'
      - 'sensor.memory_free'
      - 'sensor.memory_use'
      - 'sensor.memory_use_percent'
      - 'sensor.processor_use_percent'
      - 'sensor.processor_temperature'
  - path: 'network'
    title: 'Network'
    badges:
      - 'sensor.speedtest_ping'
      - 'sensor.speedtest_download'
      - 'sensor.speedtest_upload'
