---
alias: 'Notification when basement dehumidifier stops'
id: '38fb4e0b-0b42-4d3b-a855-444373d0a37f'
trigger:
  platform: 'numeric_state'
  entity_id: 'switch.basement_dehumidifier'
  attribute: 'current_power_w'
  below: 10
  for: 300
action:
  service: 'notify.mobile_app_josh_phone'
  data:
    title: 'Dehumidifier has stopped'
    message: 'Basement Dehumiifer has turned off, probably because the tank is full.'
