---
automation: !include_dir_list 'automations'
homeassistant:
  allowlist_external_dirs: []
  allowlist_external_urls: []
  auth_mfa_modules:
    - type: 'totp'
  auth_providers:
    - type: 'homeassistant'
  customize: !include 'customize.yaml'
  customize_domain: {}
  customize_glob:
    automation.*_night_light:
      icon: 'mdi:flashlight'
    light.bedroom_*:
      icon: 'mdi:ceiling-light'
    light.living_room_*_*:
      icon: 'mdi:track-light'
    switch.aircon_*:
      icon: 'mdi:air-conditioner'
  elevation: !secret 'home.elevation'
  external_url: !secret 'core.external_url'
  internal_url: 'http://homeassistant.local:8123'
  latitude: !secret 'home.latitude'
  longitude: !secret 'home.longitude'
  media_dirs: {}
  name: 'Home'
  packages: !include_dir_named 'packages'
  time_zone: 'Australia/Sydney'
person:
  - device_trackers:
      - 'device_tracker.josh_phone'
    id: 'josh'
    name: 'Joshua Spence'
    user_id: '480722be90284576b6f3ad7596843dfa'
  - device_trackers:
      - 'device_tracker.lily_phone'
    id: 'lily'
    name: 'Amelia Spence'
    user_id: '71917d714b7345a1a1a2ad6caf9c500e'
scene: !include_dir_list 'scenes'
script: !include_dir_named 'scripts'
zone:
  - icon: 'mdi:home'
    latitude: !secret 'home.latitude'
    longitude: !secret 'home.longitude'
    name: 'Home'
    radius: 50
