---
homeassistant:
  allowlist_external_dirs: []
  allowlist_external_urls: []
  auth_mfa_modules:
    - type: 'totp'
  auth_providers:
    - type: 'homeassistant'
  customize:
    binary_sensor.josh_phone_is_charging:
      # yamllint disable-line rule:quoted-strings
      friendly_name: "Josh's Phone Charging"
    binary_sensor.lily_phone_is_charging:
      # yamllint disable-line rule:quoted-strings
      friendly_name: "Lily's Phone Charging"
    binary_sensor.workday:
      icon: 'mdi:calendar'
    light.dining_room:
      icon: 'mdi:ceiling-light'
    sensor.disk_free:
      friendly_name: 'Disk free'
    sensor.disk_use:
      friendly_name: 'Disk use'
    sensor.disk_use_percent:
      friendly_name: 'Disk use'
    sensor.memory_use_percent:
      friendly_name: 'Memory use'
    sensor.processor_temperature:
      icon: 'mdi:mdi-thermometer'
    sensor.processor_use:
      friendly_name: 'Processor use'
  customize_domain: {}
  customize_glob:
    light.bedroom_*:
      icon: 'mdi:ceiling-light'
    light.living_room_*_*:
      icon: 'mdi:track-light'
    media_player.*_display: {}
    media_player.*_speaker:
      device_class: 'speaker'
      icon: 'mdi:speaker'
    media_player.*_tv:
      device_class: 'tv'
      icon: 'mdi:television'
    sensor.caltex_woolworths_*:
      icon: 'mdi:gas-station'
    switch.aircon_*:
      icon: 'mdi:air-conditioner'
  elevation: !secret 'home.elevation'
  external_url: !secret 'core.external_url'
  internal_url: 'http://homeassistant.local:8123'
  latitude: !secret 'home.latitude'
  longitude: !secret 'home.longitude'
  media_dirs: {}
  name: 'Home'
  packages: !include_dir_named 'integrations'
  time_zone: 'Australia/Sydney'
