# yamllint disable rule:empty-values rule:key-ordering rule:quoted-strings
---
automation: {}
cloud: {}
config: {}
frontend: {}
history: {}
image: {}
input_boolean: {}
input_datetime: {}
input_number: {}
input_select: {}
input_text: {}
logbook: {}
map: {}
media_source: {}
mobile_app: {}
person: {}
scene: {}
script: {}
ssdp: {}
sun: {}
system_health: {}
tag: {}
updater: {}
zeroconf: {}
zone: {}

# Text to speech
tts:
  - platform: 'google_translate'

# See https://www.home-assistant.io/docs/configuration/basic/.
homeassistant:
  name: 'Home'
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 11
  unit_system: 'metric'
  temperature_unit: 'C'
  time_zone: 'Australia/Sydney'
  external_url: 'https://hass.spence.network'
  internal_url: 'http://localhost:8123'
  customize: {}

device_tracker:
  - platform: 'linksys_smart'
    host: '10.158.145.48'
