# yamllint disable rule:empty-values rule:key-ordering rule:quoted-strings
---
default_config: {}

# Text to speech
tts:
  - platform: 'google_translate'

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
