---
automation: !include_dir_list 'automations'
homeassistant:
  allowlist_external_dirs: []
  allowlist_external_urls: []
  auth_mfa_modules:
    - type: 'totp'
  auth_providers:
    - type: 'homeassistant'
  customize:
    light.dining_room:
      icon: 'mdi:ceiling-light'
  customize_domain: {}
  customize_glob:
    light.bedroom_*:
      icon: 'mdi:ceiling-light'
    light.living_room_*_*:
      icon: 'mdi:track-light'
    sensor.caltex_woolworths_*:
      icon: 'mdi:gas-station'
    switch.aircon_*:
      icon: 'mdi:air-conditioner'
  elevation: !secret 'home.elevation'
  external_url: !secret 'core.external_url'
  internal_url: 'http://homeassistant.local:8123'
  latitude: !secret 'home.latitude'
  longitude: !secret 'home.longitude'
  media_dirs: {}
  name: 'Home'
  packages: !include_dir_named 'packages'
  time_zone: 'Australia/Sydney'
scene: !include_dir_list 'scenes'
script: !include_dir_named 'scripts'
