---
homeassistant:
  allowlist_external_dirs: []
  allowlist_external_urls: []
  auth_mfa_modules:
    - type: 'totp'
  auth_providers:
    - type: 'homeassistant'
  customize:
    binary_sensor.workday:
      icon: 'mdi:office-building'
  customize_domain: {}
  customize_glob:
    sensor.caltex_woolworths_*:
      icon: 'mdi:gas-station'
  elevation: !secret 'elevation'
  external_url: !secret 'external_url'
  internal_url: 'http://localhost:8123'
  latitude: !secret 'latitude'
  longitude: !secret 'longitude'
  media_dirs: {}
  name: 'Home'
  packages: !include_dir_named 'integrations'
  time_zone: 'Australia/Sydney'
