---
automation: !include_dir_list 'automations'
default_config: {}
group:
  family:
    entities:
      - 'person.josh'
      - 'person.lily'
    icon: 'mdi:human-male-female'
    name: 'Family'
homeassistant:
  allowlist_external_dirs: []
  allowlist_external_urls: []
  auth_mfa_modules:
    - type: 'totp'
  auth_providers:
    - type: 'homeassistant'
  customize: !include 'customize.yaml'
  customize_domain: {}
  customize_glob:
    automation.*_motion_lights:
      icon: 'mdi:motion-sensor'
    binary_sensor.*_door:
      device_class: 'door'
    binary_sensor.*_window:
      device_class: 'window'
    light.bedroom_*:
      icon: 'mdi:ceiling-light'
    light.living_room_*_*:
      icon: 'mdi:track-light'
    media_player.*_speaker:
      device_class: 'speaker'
      icon: 'mdi:speaker'
  elevation: !secret 'home.elevation'
  external_url: !secret 'core.external_url'
  internal_url: 'http://homeassistant.local'
  latitude: !secret 'home.latitude'
  longitude: !secret 'home.longitude'
  media_dirs: {}
  name: 'Home'
  packages: !include_dir_named 'packages'
  time_zone: 'Australia/Sydney'
http:
  server_port: 80
lovelace:
  mode: 'yaml'
  dashboards: !include 'lovelace/dashboards.yaml'
  resources: !include 'lovelace/resources.yaml'
person:
  # TODO: Specify `picture`.
  - id: 'josh'
    name: 'Joshua Spence'
    user_id: '480722be90284576b6f3ad7596843dfa'
    device_trackers:
      - 'device_tracker.josh_phone_app'
      - 'device_tracker.josh_phone_unifi'
  - id: 'lily'
    name: 'Amelia Spence'
    user_id: '71917d714b7345a1a1a2ad6caf9c500e'
    device_trackers:
      - 'device_tracker.lily_phone_app'
      - 'device_tracker.lily_phone_unifi'
  - id: 'michael'
    name: 'Michael Spence'
    device_trackers:
      - 'device_tracker.michael_phone'
scene: !include_dir_list 'scenes'
script: !include_dir_named 'scripts'
zone:
  - icon: 'mdi:home'
    latitude: !secret 'home.latitude'
    longitude: !secret 'home.longitude'
    name: 'Home'
    radius: 50
