---
automation: !include_dir_list 'automations'
default_config: null
group:
  family:
    entities:
      - 'person.josh'
      - 'person.lily'
    icon: 'mdi:human-male-female-child'
    name: 'Family'
homeassistant:
  allowlist_external_dirs: []
  allowlist_external_urls: []
  auth_mfa_modules:
    - type: 'totp'
  auth_providers:
    - type: 'homeassistant'
  currency: 'AUD'
  customize: !include 'customize.yaml'
  customize_domain: {}
  customize_glob:
    automation.*_motion_lights:
      icon: 'mdi:motion-sensor'
    binary_sensor.*_door:
      device_class: 'door'
    binary_sensor.*_window:
      device_class: 'window'
    device_tracker.*_laptop:
      icon: 'mdi:laptop'
    device_tracker.*_laptop_*:
      icon: 'mdi:laptop'
    device_tracker.*_phone:
      icon: 'mdi:cellphone'
    device_tracker.*_phone_*:
      icon: 'mdi:cellphone'
    light.bedroom_*:
      icon: 'mdi:ceiling-light'
    light.living_room_*_*:
      icon: 'mdi:track-light'
    media_player.*_speaker:
      device_class: 'speaker'
      icon: 'mdi:speaker'
    switch.aircon_*:
      icon: 'mdi:hvac'
  elevation: !secret 'home.elevation'
  external_url: !secret 'core.external_url'
  internal_url: 'https://homeassistant.spence.network'
  latitude: !secret 'home.latitude'
  longitude: !secret 'home.longitude'
  name: 'Home'
  packages: !include_dir_named 'packages'
  time_zone: 'Australia/Sydney'
http:
  server_port: 443
  ssl_certificate: !secret 'http.ssl_certificate'
  ssl_key: !secret 'http.ssl_key'
lovelace:
  mode: 'yaml'
  dashboards: !include 'lovelace/dashboards.yaml'
  resources: !include 'lovelace/resources.yaml'
person:
  # TODO: Specify `picture`.
  - id: 'josh'
    name: 'Joshua Spence'
    user_id: '480722be90284576b6f3ad7596843dfa'
    device_trackers:
      - 'device_tracker.josh_phone_app'
      - 'device_tracker.josh_phone_unifi'
  - id: 'lily'
    name: 'Amelia Spence'
    user_id: '71917d714b7345a1a1a2ad6caf9c500e'
    device_trackers:
      - 'device_tracker.lily_phone_app'
      - 'device_tracker.lily_phone_unifi'
scene: !include_dir_list 'scenes'
script: !include_dir_named 'scripts'
zone:
  - icon: 'mdi:home'
    latitude: !secret 'home.latitude'
    longitude: !secret 'home.longitude'
    name: 'Home'
    radius: 50
  - icon: 'mdi:office-building'
    latitude: !secret 'work.latitude'
    longitude: !secret 'work.longitude'
    name: 'Work'
