# yamllint disable rule:key-ordering
---
automation: {}
cloud: {}
image: {}
input_boolean: {}
input_datetime: {}
input_number: {}
input_select: {}
input_text: {}
map: {}
media_source: {}
mobile_app: {}
person: {}
scene: {}
script: {}
ssdp: {}
tag: {}
tts:
  - platform: 'google_translate'
updater: {}
zeroconf: {}
zone: {}

# See https://www.home-assistant.io/docs/configuration/basic/.
homeassistant:
  name: 'Home'
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 11
  unit_system: 'metric'
  temperature_unit: 'C'
  time_zone: 'Australia/Sydney'
  external_url: 'https://hass.spence.network'
  internal_url: 'http://localhost:8123'
  customize: {}
  packages: !include_dir_named integrations

device_tracker:
  - platform: 'linksys_smart'
    host: '10.158.145.48'
