---
homeassistant:
  allowlist_external_dirs: []
  allowlist_external_urls: []
  customize: {}
  customize_domain: {}
  customize_glob: {}
  elevation: !secret 'elevation'
  external_url: !secret 'external_url'
  internal_url: 'http://localhost:8123'
  latitude: !secret 'latitude'
  longitude: !secret 'longitude'
  media_dirs: {}
  name: 'Home'
  packages: !include_dir_named 'integrations'
  time_zone: 'Australia/Sydney'
