---
homeassistant:
  allowlist_external_dirs: []
  allowlist_external_urls: []
  auth_mfa_modules:
    - type: 'totp'
  auth_providers:
    - type: 'homeassistant'
  customize:
    binary_sensor.josh_phone_is_charging:
      # yamllint disable-line rule:quoted-strings
      friendly_name: "Josh's Phone Charging"
    binary_sensor.lily_phone_is_charging:
      # yamllint disable-line rule:quoted-strings
      friendly_name: "Lily's Phone Charging"
    binary_sensor.workday:
      icon: 'mdi:office-building'
  customize_domain: {}
  customize_glob:
    sensor.caltex_woolworths_*:
      icon: 'mdi:gas-station'
    switch.aircon_*:
      icon: 'mdi:air-conditioner'
  elevation: !secret 'home.elevation'
  external_url: !secret 'core.external_url'
  internal_url: 'http://homeassistant.local:8123'
  latitude: !secret 'home.latitude'
  longitude: !secret 'home.longitude'
  media_dirs: {}
  name: 'Home'
  packages: !include_dir_named 'integrations'
  time_zone: 'Australia/Sydney'
