---
version: '3'

tasks:
  reload:
    deps:
      - 'reload-automations'
      - 'reload-core-config'
      - 'reload-groups'
      - 'reload-inputs'
      - 'reload-persons'
      - 'reload-scenes'
      - 'reload-scripts'
      - 'reload-zones'
  reload-automations:
    cmds:
      - 'hass-cli service call automation.reload'
    sources:
      - 'integrations/automation.yaml'
      - 'automations/**.yaml'
  reload-core-config:
    cmds:
      - 'hass-cli service call homeassistant.reload_core_config'
  reload-groups:
    cmds:
      - 'hass-cli service call group.reload'
    sources:
      - 'integrations/group.yaml'
      - 'entities/groups/**.yaml'
  reload-inputs:
    cmds:
      - 'hass-cli service call input_boolean.reload'
      - 'hass-cli service call input_datetime.reload'
      - 'hass-cli service call input_number.reload'
      - 'hass-cli service call input_select.reload'
      - 'hass-cli service call input_text.reload'
    sources:
      - 'integrations/input.yaml'
  reload-persons:
    cmds:
      - 'hass-cli service call person.reload'
    sources:
      - 'integrations/person.yaml'
      - 'entities/persons/**.yaml'
  reload-scenes:
    cmds:
      - 'hass-cli service call scene.reload'
    sources:
      - 'integrations/scene.yaml'
      - 'scenes/**.yaml'
  reload-scripts:
    cmds:
      - 'hass-cli service call script.reload'
    sources:
      - 'integrations/script.yaml'
  reload-zones:
    cmds:
      - 'hass-cli service call zone.reload'
    sources:
      - 'integrations/zone.yaml'
      - 'entities/zones/**.yaml'
