---
version: '3'

tasks:
  reload-automations:
    cmd: 'hass-cli service call automation.reload'
  reload-core-config:
    cmd: 'hass-cli service call homeassistant.reload_core_config'
  reload-groups:
    cmd: 'hass-cli service call group.reload'
  reload-inputs:
    cmds:
      - 'hass-cli service call input_boolean.reload'
      - 'hass-cli service call input_datetime.reload'
      - 'hass-cli service call input_number.reload'
      - 'hass-cli service call input_select.reload'
      - 'hass-cli service call input_text.reload'
  reload-persons:
    cmd: 'hass-cli service call person.reload'
  reload-scenes:
    cmd: 'hass-cli service call scene.reload'
  reload-scripts:
    cmd: 'hass-cli service call script.reload'
  reload-zones:
    cmd: 'hass-cli service call zone.reload'
