# yamllint disable rule:key-ordering
---
title: 'Home'
views:
  - path: 'default_view'
    title: 'Home'
    badges:
      - entity: 'person.josh'
      - entity: 'person.lily'
      - entity: 'sensor.daikin_ac_inside_temperature'
    cards:
      - type: 'entities'
        entities:
          - 'light.bedroom_1'
        title: 'Bedroom 1'
      - type: 'entities'
        entities:
          - 'light.bedroom_2'
        title: 'Bedroom 2'
      - type: 'entities'
        entities:
          - 'light.dining_room'
        title: 'Dining Room'
      - type: 'entities'
        entities:
          - entity: 'light.hallway_east'
            name: 'East'
          - entity: 'light.hallway_west'
            name: 'West'
        title: 'Hallway'
      - type: 'entities'
        entities:
          - 'light.kitchen'
        title: 'Kitchen'
      - type: 'entities'
        entities:
          - 'light.laundry'
        title: 'Laundry'
      - type: 'entities'
        entities:
          - entity: 'light.living_room_upper_east'
            name: 'Upper East'
          - entity: 'light.living_room_lower_east'
            name: 'Lower East'
          - entity: 'light.living_room_lower_west'
            name: 'Lower West'
          - entity: 'light.living_room_upper_west'
            name: 'Upper West'
        title: 'Living Room'
      - type: 'entities'
        entities:
          - entity: 'light.outside_sse'
            name: 'South-southeast'
          - entity: 'light.outside_nnw'
            name: 'North-northwest'
          - entity: 'light.outside_nne'
            name: 'North-northeast'
          - entity: 'light.outside_ene'
            name: 'East-northeast'
          - entity: 'light.outside_ssw'
            name: 'South-southwest'
          - 'light.front_door'
          - entity: 'light.outside_ese'
            name: 'East-southeast'
        title: 'Outside'
      - type: 'entities'
        entities:
          - 'light.toilet'
        title: 'Toilet'
      - type: 'thermostat'
        entity: 'climate.daikin_ac'
      - type: 'entities'
        entities:
          - 'light.living_room'
          - 'light.outside_wall'
        title: 'Light'
      - type: 'entities'
        entities:
          - 'switch.aircon_downstairs'
          - 'switch.aircon_upstairs'
        title: 'Switch'
      - type: 'weather-forecast'
        entity: 'weather.home'
        show_forecast: false
      - type: 'weather-forecast'
        entity: 'weather.home_hourly'
        show_forecast: false
