---
views:
  - !include 'lovelace/views/lighting.yaml'
  - !include 'lovelace/views/climate.yaml'
  - !include 'lovelace/views/media.yaml'
  - !include 'lovelace/views/occupancy.yaml'
  - !include 'lovelace/views/system.yaml'
