---
views:
  - !include 'lovelace/views/overview.yaml'
  - !include 'lovelace/views/lighting.yaml'
  - !include 'lovelace/views/climate.yaml'
  - !include 'lovelace/views/weather.yaml'
  - !include 'lovelace/views/security.yaml'
  - !include 'lovelace/views/vacuum.yaml'
  - !include 'lovelace/views/media.yaml'
  - !include 'lovelace/views/occupancy.yaml'
  - !include 'lovelace/views/system.yaml'
