# yamllint disable rule:key-ordering
---
views:
  - title: 'Lighting'
    path: 'light'
    cards:
      - type: 'entities'
        title: 'Bedrooms'
        icon: 'mdi:bed'
        entities:
          - 'light.bedroom_1'
          - 'light.bedroom_2'

      - type: 'entities'
        title: 'Dining Room'
        icon: 'mdi:silverware-fork-knife'
        entities:
          - 'light.dining_room'

      - type: 'entities'
        title: 'Hallway'
        entities:
          - entity: 'light.hallway_east'
            name: 'East'
          - entity: 'light.hallway_west'
            name: 'West'

      - type: 'entities'
        title: 'Kitchen'
        icon: 'mdi:fridge'
        entities:
          - 'light.kitchen'

      - type: 'entities'
        title: 'Laundry'
        icon: 'mdi:washing-machine'
        entities:
          - 'light.laundry'

      - type: 'entities'
        title: 'Living Room'
        icon: 'mdi:television'
        show_header_toggle: false
        entities:
          - entity: 'light.living_room'
            name: 'All'
          - type: 'divider'
          - entity: 'light.living_room_lower_east'
            name: 'Lower East'
          - entity: 'light.living_room_lower_west'
            name: 'Lower West'
          - entity: 'light.living_room_upper_east'
            name: 'Upper East'
          - entity: 'light.living_room_upper_west'
            name: 'Upper West'

      - type: 'entities'
        title: 'Outside'
        icon: 'mdi:tree'
        show_header_toggle: false
        entities:
          - 'light.front_door'
          - 'light.outside_wall'
          - type: 'divider'
          - entity: 'light.outside_nne'
            name: 'North-northeast'
          - entity: 'light.outside_ene'
            name: 'East-northeast'
          - entity: 'light.outside_ese'
            name: 'East-southeast'
          - entity: 'light.outside_sse'
            name: 'South-southeast'
          - entity: 'light.outside_ssw'
            name: 'South-southwest'
          - entity: 'light.outside_nnw'
            name: 'North-northwest'

      - type: 'entities'
        title: 'Toilet'
        icon: 'mdi:toilet'
        entities:
          - 'light.toilet'

  - title: 'Aircon'
    path: 'climate'
    cards:
      - type: 'thermostat'
        entity: 'climate.daikin_ac'

      - type: 'vertical-stack'
        title: 'Downstairs'
        cards:
          - type: 'button'
            entity: 'switch.aircon_downstairs'
            show_name: false
            show_state: true
            icon_height: '30px'
          - type: 'glance'
            entities: &downstairs_temperature_entities
              - entity: 'sensor.kitchen_temperature'
                name: 'Kitchen'
              - entity: 'sensor.laundry_door_temperature'
                name: 'Laundry'
              - entity: 'sensor.living_room_temperature'
                name: 'Living Room'
          - type: 'history-graph'
            entities: *downstairs_temperature_entities

      - type: 'vertical-stack'
        title: 'Upstairs'
        cards:
          - type: 'button'
            entity: 'switch.aircon_upstairs'
            show_name: false
            show_state: true
            icon_height: '30px'
          - type: 'glance'
            entities: &upstairs_temperature_entities
              - entity: 'sensor.front_door_temperature'
                name: 'Front Door'
              - entity: 'sensor.hallway_temperature'
                name: 'Hallway'
          - type: 'history-graph'
            entities: *upstairs_temperature_entities

      - type: 'vertical-stack'
        title: 'Outside'
        cards:
          - type: 'glance'
            entities: &outside_temperature_entities
              - entity: 'sensor.front_yard_temperature'
                name: 'Front Yard'
          - type: 'history-graph'
            entities: *outside_temperature_entities

  - title: 'Weather'
    path: 'weather'
    cards:
      - type: 'weather-forecast'
        entity: 'weather.home_hourly'
        name: 'Hourly'
        show_forecast: true
      - type: 'weather-forecast'
        entity: 'weather.home'
        name: 'Daily'
        show_forecast: true

  - title: 'Media'
    path: 'media'
    cards:
      - type: 'media-control'
        entity: 'media_player.kitchen_display'
      - type: 'media-control'
        entity: 'media_player.living_room_speaker'
      - type: 'media-control'
        entity: 'media_player.living_room_tv'
      - type: 'media-control'
        entity: 'media_player.office_display'

  - title: 'Map'
    path: 'map'
    cards:
      - type: 'map'
        entities:
          - 'person.josh'
          - 'person.lily'
          - 'zone.home'
