# yamllint disable rule:key-ordering
---
views:
  - title: 'Lighting'
    path: 'light'
    cards:
      - type: 'entities'
        title: 'Bedrooms'
        icon: 'mdi:bed'
        entities:
          - 'light.bedroom_1'
          - 'light.bedroom_2'

  - title: 'Aircon'
    path: 'climate'
    cards:
      - type: 'thermostat'
        entity: 'climate.daikin_ac'

      - type: 'vertical-stack'
        title: 'Downstairs'
        cards:
          - type: 'button'
            entity: 'switch.aircon_downstairs'
            show_name: false
            show_state: true
          - type: 'glance'
            entities:
              - entity: 'sensor.kitchen_temperature'
                name: 'Kitchen'
              - entity: 'sensor.laundry_door_temperature'
                name: 'Laundry'
              - entity: 'sensor.living_room_temperature'
                name: 'Living Room'
          - type: 'history-graph'
            entities:
              - entity: 'sensor.kitchen_temperature'
                name: 'Kitchen'
              - entity: 'sensor.laundry_door_temperature'
                name: 'Laundry'
              - entity: 'sensor.living_room_temperature'
                name: 'Living Room'

      - type: 'vertical-stack'
        title: 'Upstairs'
        cards:
          - type: 'button'
            entity: 'switch.aircon_upstairs'
            show_name: false
            show_state: true
          - type: 'glance'
            entities:
              - entity: 'sensor.front_door_temperature'
                name: 'Front Door'
              - entity: 'sensor.hallway_temperature'
                name: 'Hallway'
          - type: 'history-graph'
            entities:
              - entity: 'sensor.front_door_temperature'
                name: 'Front Door'
              - entity: 'sensor.hallway_temperature'
                name: 'Hallway'

      - type: 'vertical-stack'
        title: 'Outside'
        cards:
          - type: 'glance'
            entities:
              - entity: 'sensor.front_yard_temperature'
                name: 'Front Yard'
          - type: 'history-graph'
            entities:
              - entity: 'sensor.front_yard_temperature'
                name: 'Front Yard'
