---
id: 'e389a147-b6a7-4191-ad2c-82517c8d56f4'
alias: 'living_room_west_shelly Buttons'
use_blueprint:
  path: 'esphome_buttons.yaml'
  input:
    device: 'living_room_west_shelly'
    button1_click:
      service: 'light.toggle'
      data:
        entity_id: 'light.living_room_upper_west'
    button2_click:
      service: 'light.toggle'
      data:
        entity_id: 'light.living_room_lower_west'
