---
id: '048e933b-c33d-43cb-8907-fc9cda9fc39a'
alias: 'toilet_shelly Buttons'
use_blueprint:
  path: 'esphome_buttons.yaml'
  input:
    device: 'toilet_shelly'
    button1_click:
      service: 'light.toggle'
      data:
        entity_id: 'light.toilet'
    button2_click:
      service: 'fan.toggle'
      data:
        entity_id: 'fan.toilet'
