---
uart:
  id: 'uart_bus'
  rx_pin:
    number: 'GPIO5'
    ignore_strapping_warning: true
  tx_pin: 'GPIO16'
  baud_rate: 115200

external_components:
  # Pinned to the tip of the `get_use_address_to` branch.
  - source: 'github://grob6000/esphome-stream-server@2eade8f0ec9c5282631e09af95f08b634c6a5c20'

stream_server:
  uart_id: 'uart_bus'

binary_sensor:
  - platform: 'stream_server'
    connected:
      name: 'Connected'

sensor:
  - platform: 'stream_server'
    connection_count:
      name: 'Connections'
      unit_of_measurement: 'connections'
