---
title: 'Security'
icon: 'mdi:security'
path: 'security'
cards:
  - type: 'alarm-panel'
    entity: 'alarm_control_panel.alarm'

  - type: 'entities'
    title: 'Exterior Doors'
    icon: 'mdi:door'
    entities:
      - 'binary_sensor.front_door'
      - 'binary_sensor.back_door'
      - 'binary_sensor.living_room_sliding_door'
      - 'binary_sensor.dining_room_sliding_door'

  - type: 'entities'
    title: 'Interior Doors'
    icon: 'mdi:door'
    entities:
      - 'binary_sensor.attic_door'
      - 'binary_sensor.bathroom_door'
      - 'binary_sensor.bedroom_1_door'
      - 'binary_sensor.bedroom_2_door'
      - 'binary_sensor.kitchen_door'
      - 'binary_sensor.laundry_door'
      - 'binary_sensor.linen_closet_door'
      - 'binary_sensor.office_door'
      - 'binary_sensor.toilet_door'
