---
title: 'Security'
icon: 'mdi:security'
path: 'security'
cards:
  - type: 'alarm-panel'
    entity: &alarm 'alarm_control_panel.alarm'
    states:
      - 'arm_home'
      - 'arm_away'
      - 'arm_night'

  - type: 'entities'
    entities:
      - type: 'custom:decluttering-card'
        template: 'fold_entity_row'
        variables:
          - head_entity: &external_doors 'binary_sensor.external_doors'
      - type: 'custom:decluttering-card'
        template: 'fold_entity_row'
        variables:
          - head_entity: &external_occupancy 'binary_sensor.external_occupancy'
          - row_trim_suffix: 'Occupancy'
      - type: 'custom:decluttering-card'
        template: 'fold_entity_row'
        variables:
          - head_entity: &internal_doors 'binary_sensor.internal_doors'
          - row_trim_suffix: 'Door'
      - type: 'custom:decluttering-card'
        template: 'fold_entity_row'
        variables:
          - head_entity: &internal_occupancy 'binary_sensor.internal_occupancy'
          - row_trim_suffix: 'Occupancy'
      - type: 'custom:decluttering-card'
        template: 'fold_entity_row'
        variables:
          - head_entity: &locks 'group.all_locks'
          - head_name: 'Locks'
      - type: 'custom:decluttering-card'
        template: 'fold_entity_row'
        variables:
          - head_entity: &windows 'binary_sensor.all_windows'
          - head_name: 'Windows'
          - row_trim_suffix: 'Window'

  - type: 'custom:auto-entities'
    card:
      type: 'logbook'
      hours_to_show: 1
    filter:
      include:
        - entity_id: *alarm
        - group: *external_doors
        - group: *external_occupancy
        - group: *internal_doors
        - group: *internal_occupancy
        - group: *locks
        - group: *windows
