---
id: 'd3425eaf-8d22-455b-8474-e03727d6fe2b'
alias: 'Washing Machine Notification'
trigger:
  platform: 'numeric_state'
  entity_id: 'switch.washing_machine'
  attribute: 'current_power_w'
  below: 10
  for: 60
condition:
  condition: 'zone'
  entity_id: 'person.josh'
  zone: 'zone.home'
action:
  service: 'notify.mobile_app_josh_phone'
  data:
    title: 'Washing Machine finished'
    message: 'The washing machine has completed its cycle.'
