---
alias: 'Vacuum Low Battery'
id: '77a8cf42-1126-4741-be4a-17869fadcabb'
trigger:
  platform: 'numeric_state'
  entity_id: &entity_id 'vacuum.downstairs'
  attribute: 'battery_level'
  below: 20
condition:
  condition: 'not'
  conditions:
    - condition: 'state'
      entity_id: *entity_id
      attribute: 'status'
      state: 'charging'
    - condition: 'state'
      entity_id: *entity_id
      state: 'returning'
action:
  service: 'vacuum.return_to_base'
  data:
    entity_id: *entity_id
