---
id: '46e2e798-2a9d-4d8c-aa73-bb989ac33099'
alias: 'Vacuum Stuck'
trigger:
  platform: 'state'
  entity_id: &entity_id 'vacuum.downstairs'
  attribute: 'status'
  to: 'returning'
  for:
    minutes: 30
action:
  - service: 'notify.mobile_app_josh_phone'
    data:
      title: 'Vacuum Stuck'
      message: 'Vaccum has been returning to base for 30 minutes and is likely stuck.'
