---
title: 'Security'
icon: 'mdi:security'
path: 'security'
cards:
  - type: 'alarm-panel'
    entity: 'alarm_control_panel.alarm'

  - type: 'entities'
    entities:
      - 'lock.front_door'
      - type: 'custom:fold-entity-row'
        head: 'binary_sensor.external_doors'
        <<: &common_config
          group_config:
            secondary_info: 'last-changed'
      - type: 'custom:fold-entity-row'
        head: 'binary_sensor.internal_doors'
        <<: *common_config
      - type: 'custom:fold-entity-row'
        head: 'binary_sensor.all_windows'
        <<: *common_config

  - type: 'entities'
    entities:
      - type: 'custom:fold-entity-row'
        head: 'binary_sensor.external_occupancy'
        <<: *common_config
      - type: 'custom:fold-entity-row'
        head: 'binary_sensor.internal_occupancy'
        <<: *common_config
