---
title: 'Security'
icon: 'mdi:security'
path: 'security'
cards:
  - type: 'alarm-panel'
    entity: 'alarm_control_panel.alarm'

  - type: 'custom:auto-entities'
    card:
      type: 'entities'
      title: 'Exterior Doors'
      icon: 'mdi:door'
    filter:
      include: &exterior_doors
        - entity_id: 'binary_sensor.front_door'
        - entity_id: 'lock.front_door'
        - entity_id: 'binary_sensor.back_door'
        - entity_id: 'binary_sensor.living_room_sliding_door'
        - entity_id: 'binary_sensor.dining_room_sliding_door'

  - type: 'custom:auto-entities'
    card:
      type: 'entities'
      title: 'Interior Doors'
      icon: 'mdi:door'
    filter:
      include:
        - domain: 'binary_sensor'
          entity_id: 'binary_sensor.*_door'
          attributes:
            device_class: 'door'
          options:
            type: 'custom:template-entity-row'
            name: >-
              {{ state_attr(config.entity, 'friendly_name') | replace(' Door', '') }}
            state: >-
              {% if config.entity.state == "on" %}
                Open
              {% else %}
                Closed
              {% endif %}
      exclude:
        - area: 'outside'
        - entity_id: 'binary_sensor.mailbox_*_door'
        - or: *exterior_doors
    sort:
      method: 'name'
