---
title: 'Security'
icon: 'mdi:security'
path: 'security'
cards:
  - type: 'alarm-panel'
    entity: 'alarm_control_panel.alarm'

  - type: 'entities'
    entities:
      - 'lock.front_door'
      - type: 'custom:fold-entity-row'
        head: 'binary_sensor.exterior_doors'
      - type: 'custom:fold-entity-row'
        head: 'binary_sensor.interior_doors'
      - type: 'custom:fold-entity-row'
        head: 'binary_sensor.all_windows'
