---
title: 'Security'
icon: 'mdi:security'
path: 'security'
cards:
  - type: 'alarm-panel'
    entity: 'alarm_control_panel.alarm'

  - type: 'entities'
    entities:
      - 'lock.front_door'
      - type: 'custom:fold-entity-row'
        head:
          type: 'section'
          label: 'Exterior Doors'
        entities:
          - 'binary_sensor.front_door'
          - 'binary_sensor.back_door'
          - 'binary_sensor.living_room_sliding_door'
          - 'binary_sensor.dining_room_sliding_door'
      - type: 'custom:fold-entity-row'
        head:
          type: 'section'
          label: 'Interior Doors'
        entities:
          - entity: 'binary_sensor.attic_door'
            name: 'Attic'
          - entity: 'binary_sensor.basement_door'
            name: 'Basement'
          - entity: 'binary_sensor.bathroom_door'
            name: 'Bathroom'
          - entity: 'binary_sensor.bedroom_1_door'
            name: 'Bedroom 1'
          - entity: 'binary_sensor.bedroom_2_door'
            name: 'Bedroom 2'
          - entity: 'binary_sensor.kitchen_door'
            name: 'Kitchen'
          - entity: 'binary_sensor.laundry_door'
            name: 'Laundry'
          - entity: 'binary_sensor.linen_closet_door'
            name: 'Linen closet'
          - entity: 'binary_sensor.office_door'
            name: 'Office'
          - entity: 'binary_sensor.pantry_door'
            name: 'Pantry'
          - entity: 'binary_sensor.toilet_door'
            name: 'Toilet'
      - type: 'custom:fold-entity-row'
        head:
          type: 'section'
          label: 'Windows'
        entities:
          - entity: 'binary_sensor.bedroom_1_east_window'
            name: 'Bedroom 1 (East)'
          - entity: 'binary_sensor.bedroom_1_south_window'
            name: 'Bedroom 1 (South)'
          - entity: 'binary_sensor.bedroom_2_window'
            name: 'Bedroom 2'
          - entity: 'binary_sensor.kitchen_window'
            name: 'Kitchen'
          - entity: 'binary_sensor.laundry_window'
            name: 'Laundry'
          - entity: 'binary_sensor.office_window'
            name: 'Office'
