---
title: 'Security'
icon: 'mdi:security'
path: 'security'
cards:
  - type: 'alarm-panel'
    entity: &alarm 'alarm_control_panel.alarm'

  - type: 'entities'
    entities:
      - type: 'custom:fold-entity-row'
        head:
          entity: &all_locks 'group.all_locks'
          name: 'Locks'
      - type: 'custom:fold-entity-row'
        head: &external_doors 'binary_sensor.external_doors'

      # TODO: Remove "Door" suffix from names.
      - type: 'custom:fold-entity-row'
        head: &internal_doors 'binary_sensor.internal_doors'

      # TODO: Remove "Window" suffix from names.
      - type: 'custom:fold-entity-row'
        head:
          entity: &all_windows 'binary_sensor.all_windows'
          name: 'Windows'

  - type: 'entities'
    entities:
      - type: 'custom:fold-entity-row'
        head: &external_occupancy 'binary_sensor.external_occupancy'
      - type: 'custom:fold-entity-row'
        head: &internal_occupancy 'binary_sensor.internal_occupancy'

  - type: 'custom:auto-entities'
    card:
      type: 'logbook'
      hours_to_show: 6
    filter:
      include:
        - entity_id: *alarm
        - group: *all_locks
        - group: *all_windows
        - group: *external_doors
        - group: *external_occupancy
        - group: *internal_doors
        - group: *internal_occupancy
