---
platform: 'gpio'
pin: '${input2_gpio}'
id: 'input2'
on_multi_click:
  - timing:
      - 'ON for ${button_click_min_length} to ${button_click_max_length}'
    then:
      homeassistant.event:
        event: 'esphome.button'
        data:
          device: '${device_name}'
          button: '2'
          action: 'click'
  - timing:
      - 'ON for ${button_hold_min_length} to ${button_hold_max_length}'
    then:
      homeassistant.event:
        event: 'esphome.button'
        data:
          device: '${device_name}'
          button: '2'
          action: 'hold'
  - timing:
      - 'ON for ${button_click_min_length} to ${button_click_max_length}'
      - 'OFF for ${button_click_min_length} to ${button_click_max_length}'
      - 'ON for ${button_click_min_length} to ${button_click_max_length}'
    then:
      homeassistant.event:
        event: 'esphome.button'
        data:
          device: '${device_name}'
          button: '2'
          action: 'double-click'
internal: true
