---
alarm.code: ''
core.external_url: 'http://localhost:8123'
firebase.email: ''
firebase.private_key: ''
firebase.public_key: ''
google_assistant_sdk.client_id: ''
google_assistant_sdk.client_secret: ''
home.elevation: 0
home.latitude: 0
home.longitude: 0
letsencrypt.aws_access_key_id: ''
letsencrypt.aws_secret_access_key: ''
mqtt.password: ''
netgear_lte.password: ''
phone_number.josh: ''
phone_number.lily: ''
recorder.database_url: ''
unifi.username: ''
unifi.password: ''
work.latitude: 0
work.longitude: 0
zoom.client_id: ''
zoom.client_secret: ''
zoom.verification_token: ''
