---
alarm.code: ''
core.external_url: 'http://localhost:8123'
ecovacs.password: ''
ecovacs.username: ''
firebase.email: ''
firebase.private_key: ''
firebase.public_key: ''
hacs.github_token: ''
home.elevation: 0
home.latitude: 0
home.longitude: 0
