---
alarm.code: ''
aussie_broadband.password: ''
aussie_broadband.username: ''
core.external_url: 'http://localhost:8123'
ecovacs.password: ''
ecovacs.username: ''
firebase.email: ''
firebase.private_key: ''
firebase.public_key: ''
google_home.password: ''
hacs.github_token: ''
home.elevation: 0
home.latitude: 0
home.longitude: 0
localtuya.attic_ridge.device_id: ''
localtuya.attic_ridge.local_key: ''
localtuya.attic_1.device_id: ''
localtuya.attic_1.local_key: ''
localtuya.attic_2.device_id: ''
localtuya.attic_2.local_key: ''
localtuya.attic_3.device_id: ''
localtuya.attic_3.local_key: ''
localtuya.bedroom_1_air_purifier.device_id: ''
localtuya.bedroom_1_air_purifier.local_key: ''
localtuya.bedroom_1_ceiling_projector.device_id: ''
localtuya.bedroom_1_ceiling_projector.local_key: ''
mqtt.password: ''
netgear_lte.password: ''
phone_number.josh: ''
phone_number.lily: ''
unifi.username: ''
unifi.password: ''
zoom.client_id: ''
zoom.client_secret: ''
zoom.verification_token: ''
