---
alarm.code: ''
core.external_url: 'http://localhost:8123'
ecovacs.password: ''
ecovacs.username: ''
firebase.email: ''
firebase.private_key: ''
firebase.public_key: ''
google_home.password: ''
hacs.github_token: ''
home.elevation: 0
home.latitude: 0
home.longitude: 0
tuya.attic_ridge.device_id: ''
tuya.attic_ridge.local_key: ''
tuya.attic_1.device_id: ''
tuya.attic_1.local_key: ''
tuya.attic_2.device_id: ''
tuya.attic_2.local_key: ''
tuya.attic_3.device_id: ''
tuya.attic_3.local_key: ''
unifi.username: ''
unifi.password: ''
zoom.client_id: ''
zoom.client_secret: ''
zoom.verification_token: ''
