---
packages:
  common: !include '../../packages/common.yaml'
  platform: !include
    file: '../../packages/platform/esp32.yaml'
    vars:
      board: 'esp-wrover-kit'

esphome:
  on_boot:
    then:
      - switch.turn_on: 'zRST_gpio'
      - delay: '15ms'
      - switch.turn_off: 'zRST_gpio'

ethernet:
  type: 'LAN8720'
  mdc_pin: 'GPIO23'
  mdio_pin: 'GPIO18'
  clk_mode: 'GPIO17_OUT'
  power_pin: 'GPIO12'

# TODO: Remove this.
web_server:
  port: 80

script:
  - id: 'firmware_update_mode'
    then:
      - switch.turn_on: 'zBSL'
      - delay: '1s'
      - switch.turn_on: 'zRST_gpio'
      - delay: '1s'
      - switch.turn_off: 'zRST_gpio'
      - delay: '11s'
      - switch.turn_off: 'zBSL'
      - logger.log: 'Firmware update mode has been enabled.'

switch:
  - platform: 'gpio'
    pin: 33
    id: 'zRST_gpio'
    restore_mode: 'ALWAYS_OFF'
    inverted: true
  - platform: 'gpio'
    pin: 32
    name: 'Zigbee Module Bootloader Pin'
    id: 'zBSL'
    restore_mode: 'ALWAYS_OFF'
    inverted: true
    disabled_by_default: true
    entity_category: 'config'

button:
  - platform: 'template'
    name: 'Zigbee Module Reset'
    id: 'zRST'
    disabled_by_default: true
    entity_category: 'config'
    on_press:
      - switch.turn_on: 'zRST_gpio'
      - delay: '15ms'
      - switch.turn_off: 'zRST_gpio'

  - platform: 'template'
    name: 'Zigbee Module Bootloader'
    disabled_by_default: true
    entity_category: 'config'
    on_press:
      script.execute: 'firmware_update_mode'

uart:
  id: 'uart_bus'
  rx_pin: 'GPIO5'
  tx_pin: 'GPIO16'
  baud_rate: 115200

external_components:
  - source: 'github://oxan/esphome-stream-server'

stream_server:
  uart_id: 'uart_bus'

binary_sensor:
  - platform: 'stream_server'
    connected:
      name: 'Connected'

sensor:
  - platform: 'stream_server'
    connection_count:
      name: 'Connections'
      unit_of_measurement: 'connections'
