---
packages:
  common: !include '../../packages/common.yaml'
  platform: !include
    file: '../../packages/platform/esp32.yaml'
    vars:
      board: 'esp-wrover-kit'
  stream_server: !include 'packages/stream_server.yaml'

esphome:
  on_boot:
    then:
      button.press: 'zRST'

ethernet:
  type: 'LAN8720'
  mdc_pin: 'GPIO23'
  mdio_pin: 'GPIO18'
  clk_mode: 'GPIO17_OUT'
  power_pin: 'GPIO12'
wifi: !remove

script:
  - id: 'firmware_update_mode'
    then:
      - switch.turn_on: 'zBSL'
      - delay: '1s'
      - switch.turn_on: 'zRST_gpio'
      - delay: '1s'
      - switch.turn_off: 'zRST_gpio'
      - delay: '11s'
      - switch.turn_off: 'zBSL'
      - logger.log: 'Firmware update mode has been enabled.'
      - switch.template.publish:
          id: 'firmware_update_mode_switch'
          state: true

switch:
  - platform: 'gpio'
    pin: 33
    id: 'zRST_gpio'
    restore_mode: 'ALWAYS_OFF'
    inverted: true
  - platform: 'gpio'
    pin: 32
    name: 'Zigbee Module Bootloader Pin'
    id: 'zBSL'
    restore_mode: 'ALWAYS_OFF'
    inverted: true
    disabled_by_default: true
    entity_category: 'config'
  - platform: 'template'
    name: 'Firmware Update Mode'
    id: 'firmware_update_mode_switch'
    turn_on_action:
      script.execute: 'firmware_update_mode'
    turn_off_action:
      button.press: 'zRST'
    disabled_by_default: true
    entity_category: 'config'

button:
  - platform: 'template'
    name: 'Zigbee Module Reset'
    id: 'zRST'
    disabled_by_default: true
    entity_category: 'config'
    on_press:
      - switch.turn_on: 'zRST_gpio'
      - delay: '15ms'
      - switch.turn_off: 'zRST_gpio'
      - switch.template.publish:
          id: 'firmware_update_mode_switch'
          state: false

  - platform: 'template'
    name: 'Zigbee Module Bootloader'
    disabled_by_default: true
    entity_category: 'config'
    on_press:
      script.execute: 'firmware_update_mode'
