---
title: 'Security'
icon: 'mdi:security'
path: 'security'
cards:
  - type: 'alarm-panel'
    entity: 'alarm_control_panel.alarm'

  - type: 'custom:auto-entities'
    card:
      type: 'entities'
      title: 'Exterior Doors'
      icon: 'mdi:door'
    filter:
      include: &exterior_doors
        - entity_id: 'binary_sensor.front_door'
        - entity_id: 'lock.front_door'
        - entity_id: 'binary_sensor.back_door'
        - entity_id: 'binary_sensor.living_room_sliding_door'
        - entity_id: 'binary_sensor.dining_room_sliding_door'
