---
esphome:
  name: '${device_id}'
  friendly_name: '${device_name}'
  min_version: '2023.7.0'

api:
  encryption:
    key: !secret 'api.encryption_key'

logger:
  level: 'DEBUG'
  logs: {}

ota:
  password: !secret 'ota.password'

time:
  - platform: 'homeassistant'
  - platform: 'sntp'

button:
  - platform: 'shutdown'
    name: 'Shutdown'
    disabled_by_default: true
  - platform: 'safe_mode'
    name: 'Safe Mode'
    disabled_by_default: true
  - platform: 'restart'
    name: 'Restart'
