---
esphome:
  name: '${device_name}'
  platform: '${device_platform}'
  board: '${device_board}'
  build_path: 'build/${device_name}'

time:
  - platform: 'homeassistant'

ota: {}
logger: {}
api: {}

switch:
  - platform: 'restart'
    name: '${device_name}'
