---
esphome:
  name: '${device_name}'

${device_platform}:
  board: '${device_board}'

ota:
  password: !secret 'ota.password'

time:
  - platform: 'homeassistant'

logger: {}
api: {}

button:
  - platform: 'restart'
    name: 'Restart ${device_name}'
