---
esphome:
  name: '${device_name}'

${device_platform}:
  board: '${device_board}'

# TODO: Add `encryption`.
api:
  password: !secret 'api.password'

ota:
  password: !secret 'ota.password'

time:
  - platform: 'homeassistant'

logger: {}

button:
  - platform: 'restart'
    name: 'Restart ${device_name}'
