---
esphome:
  name: '${device_name}'

${device_platform}:
  board: '${device_board}'

api:
  encryption:
    key: !secret 'api.encryption_key'

ota:
  password: !secret 'ota.password'

time:
  - platform: 'homeassistant'

logger: {}

button:
  - platform: 'shutdown'
    name: '${device_name} Shutdown'
    disabled_by_default: true
  - platform: 'safe_mode'
    name: '${device_name} Safe Mode'
    disabled_by_default: true
  - platform: 'restart'
    name: '${device_name} Restart'
