---
esphome:
  name: '${device_id}'
  friendly_name: '${device_name}'
  area: '${device_area}'
  min_version: '2024.6.0'

api:
  encryption:
    key: !secret 'api.encryption.key'

logger:
  level: 'DEBUG'
  logs: {}

network: {}

ota:
  platform: 'esphome'
  password: !secret 'ota.password'

time:
  - platform: 'homeassistant'
  - platform: 'sntp'

binary_sensor:
  - platform: 'status'
    name: 'Status'

button:
  - platform: 'shutdown'
    name: 'Shutdown'
    disabled_by_default: true
  - platform: 'safe_mode'
    name: 'Safe Mode'
    disabled_by_default: true
  - platform: 'restart'
    name: 'Restart'
    id: 'button_restart'
