---
esphome:
  name: '${device_name}'
  platform: 'ESP8266'
  board: 'esp01_1m'
  build_path: 'build/${device_name}'

wifi:
  ssid: !secret 'wifi.ssid'
  password: !secret 'wifi.password'

  ap:
    ssid: '${device_name} Hotspot'
    password: !secret 'fallback_hotspot.password'

api: {}
captive_portal: {}
logger: {}
ota: {}
