---
substitutions:
  device_board: 'esp01_1m'
  device_platform: 'ESP8266'
  input1_gpio: 'GPIO5'
  output1_gpio: 'GPIO4'

  # NOTE: See esphome/issues#1532.
  wifi_power_save_mode: 'high'

packages:
  wifi: !include 'wifi.yaml'

binary_sensor:
  - platform: 'gpio'
    pin: '${input1_gpio}'
    id: 'input1'
    on_click:
      - min_length: '${button_click_min_length}'
        max_length: '${button_click_max_length}'
        then:
          homeassistant.event:
            event: &button_event 'esphome.shelly_button'
            data:
              device: '${device_name}'
              button: '1'
              action: 'click'
      - min_length: '${button_hold_min_length}'
        max_length: '${button_hold_max_length}'
        then:
          homeassistant.event:
            event: *button_event
            data:
              device: '${device_name}'
              button: '1'
              action: 'hold'
    on_double_click:
      min_length: '${button_click_min_length}'
      max_length: '${button_click_max_length}'
      then:
        homeassistant.event:
          event: *button_event
          data:
            device: '${device_name}'
            button: '1'
            action: 'double-click'
    internal: true
