---
wifi:
  ssid: !secret 'wifi.ssid'
  password: !secret 'wifi.password'
  ap:
    ssid: '${device_name} Hotspot'
    password: !secret 'fallback_hotspot.password'
  fast_connect: true

captive_portal: {}
