---
substitutions:
  wifi_enable_btm: 'false'
  wifi_enable_rrm: 'false'
  wifi_power_save_mode: 'none'

# TODO: Remove this after esphome/esphome#5145 is merged.
external_components:
  - source: 'github://pr#5145'
    components:
      - 'wifi'

wifi:
  networks:
    - ssid: !secret 'wifi.ssid'
      password: !secret 'wifi.password'
      hidden: true
  ap:
    password: !secret 'fallback_hotspot.password'
  power_save_mode: '${wifi_power_save_mode}'
  enable_btm: '${wifi_enable_btm}'
  enable_rrm: '${wifi_enable_rrm}'

captive_portal: {}
