---
substitutions:
  wifi_power_save_mode: 'none'

wifi:
  ssid: !secret 'wifi.ssid'
  password: !secret 'wifi.password'
  ap:
    ssid: '${device_name} Hotspot'
    password: !secret 'fallback_hotspot.password'
  power_save_mode: '${wifi_power_save_mode}'

captive_portal: {}
