---
wifi:
  networks:
    - ssid: !secret 'wifi.ssid'
      password: !secret 'wifi.password'
      hidden: true
  ap:
    password: !secret 'wifi.ap.password'

# TODO: Use Improv instead of captive portal.
captive_portal: {}
