---
wifi:
  networks:
    - ssid: !secret 'wifi.ssid'
      password: !secret 'wifi.password'
      hidden: true
  ap:
    password: !secret 'fallback_hotspot.password'
  power_save_mode: '${wifi_power_save_mode}'

captive_portal: {}
