---
wifi:
  networks:
    - ssid: !secret 'wifi.ssid'
      password: !secret 'wifi.password'
      hidden: true
  ap:
    ssid: '${device_name} Hotspot'
    password: !secret 'fallback_hotspot.password'

captive_portal: {}
