---
substitutions:
  device_board: 'esp01_1m'
  device_platform: 'ESP8266'

output:
  - platform: 'esp8266_pwm'
    pin: 14
    id: 'output_blue'
  - platform: 'esp8266_pwm'
    pin: 12
    id: 'output_green'
  - platform: 'esp8266_pwm'
    pin: 4
    id: 'output_red'
  - platform: 'esp8266_pwm'
    pin: 5
    id: 'output_coldwhite'
  - platform: 'esp8266_pwm'
    pin: 13
    id: 'output_warmwhite'

light:
  - platform: 'rgbww'
    name: '${output_name}'
    red: 'output_red'
    green: 'output_green'
    blue: 'output_blue'
    cold_white: 'output_coldwhite'
    warm_white: 'output_warmwhite'
    cold_white_color_temperature: '6500 K'
    warm_white_color_temperature: '2700 K'
    default_transition_length: '0s'
