---
blueprint:
  name: 'Add-on Update Notification'
  domain: 'automation'
  input:
    addon:
      name: 'Add-on'
      selector:
        addon: null
    sensor:
      name: 'Update Sensor'
      selector:
        entity:
          domain: 'update'
          integration: 'hassio'

trigger:
  platform: 'state'
  entity_id: !input 'sensor'
action:
  choose:
    - conditions: '{{ trigger.to_state.state == "on" }}'
      sequence:
        service: 'persistent_notification.create'
        data:
          title: '{{ state_attr(sensor, "title") }} Update Available'
          message: >-
            An update is available for [{{ state_attr(sensor, 'title') }} add-on](/hassio/addon/{{ addon }}/info).

            **Installed Version:** {{ state_attr(sensor, 'installed_version') }}
            **Latest Version:** {{ state_attr(sensor, 'latest_version') }}
            **Release Summary:** {{ state_attr(sensor, 'release_summary') }}
          notification_id: 'update_available_{{ addon }}'
    - conditions: '{{ trigger.to_state.state == "off" }}'
      sequence:
        service: 'persistent_notification.dismiss'
        data:
          notification_id: 'update_available_{{ addon }}'

mode: 'single'
max_exceeded: 'silent'
