---
blueprint:
  name: 'Door-Activated Lights'
  description: >-
    Turn lights on/off based on door closure and ambient light.

    The targeted lights will turn on when the door is opened, unless the
    ambient light level exceeds a configured threshold. The targeted lights
    will turn off when the door is closed for a duration of `off_delay`.
  domain: 'automation'
  input:
    trigger_sensor:
      name: 'Door Sensor'
      selector:
        entity:
          domain: 'binary_sensor'
          device_class: 'door'
          multiple: true
    light_target:
      name: 'Target Lights'
      selector:
        entity:
          domain: 'light'
          multiple: true

    illuminance_sensor:
      name: 'Illuminance Sensor'
      default: []
      selector:
        entity:
          domain: 'sensor'
          device_class: 'illuminance'
    illuminance_threshold:
      name: 'Illuminance Threshold'
      default: 100
      selector:
        number:
          min: 0
          max: 1000
          step: 10
          unit_of_measurement: 'lx'

    off_delay:
      name: 'Off Delay'
      default: 300
      selector:
        duration: null

trigger:
  platform: 'state'
  entity_id: !input 'trigger_sensor'
  from: 'off'
  to: 'on'

condition:
  # If the target lights are already on then they must've been turned on manually.
  - not:
      condition: 'state'
      entity_id: !input 'light_target'
      state: 'on'

  - condition: 'numeric_state'
    entity_id: !input 'illuminance_sensor'
    below: !input 'illuminance_threshold'

action:
  - action: 'light.turn_on'
    entity_id: !input 'light_target'
  - wait_for_trigger:
      - platform: 'state'
        entity_id: !input 'trigger_sensor'
        from: 'on'
        to: 'off'
        for: !input 'off_delay'
      - platform: 'state'
        entity_id: !input 'light_target'
        to: 'off'
  - action: 'light.turn_off'
    entity_id: !input 'light_target'

mode: 'single'
max_exceeded: 'silent'
trace:
  stored_traces: 10
