---
blueprint:
  name: 'Hue Dimmer Switch'
  domain: 'automation'
  input:
    remote:
      name: 'Remote'
      selector:
        device:
          integration: 'zha'
          manufacturer: 'Philips'
          model: 'RWL021'

    on_press:
      name: 'On Press'
      <<: &common_config
        default: []
        selector:
          action: {}
    up_press:
      name: 'Up Press'
      <<: *common_config
    down_press:
      name: 'Down Press'
      <<: *common_config
    off_press:
      name: 'Off Press'
      <<: *common_config

trigger:
  platform: 'event'
  event_type: 'zha_event'
  event_data:
    device_id: !input 'remote'

condition:
  condition: 'template'
  value_template: >-
    {{ 'button' in trigger.event.data.args }}

action:
  - variables:
      button: '{{ trigger.event.data.args.button }}'
      command: '{{ trigger.event.data.command }}'
      press_type: '{{ trigger.event.data.args.button }}'
  - choose:
      - conditions: '{{ button == "on" and press_type != "short_release" }}'
        sequence: !input 'on_press'
      - conditions: '{{ button == "up" and press_type != "short_release" }}'
        sequence: !input 'up_press'
      - conditions: '{{ button == "down" and press_type != "short_release" }}'
        sequence: !input 'down_press'
      - conditions: '{{ button == "off" and press_type != "short_release" }}'
        sequence: !input 'off_press'

mode: 'queued'
max_exceeded: 'silent'
