---
blueprint:
  name: 'Hue Dimmer Switch'
  domain: 'automation'
  input:
    remote:
      name: 'Remote'
      selector:
        device:
          integration: 'zha'
          manufacturer: 'Philips'
          model: 'RWL021'

    on_press:
      name: 'On Press'
      <<: &common_config
        default: []
        selector:
          action: {}
    up_press:
      name: 'Up Press'
      <<: *common_config
    down_press:
      name: 'Down Press'
      <<: *common_config
    off_press:
      name: 'Off Press'
      <<: *common_config

trigger:
  platform: 'event'
  event_type: 'zha_event'
  event_data:
    device_id: !input 'remote'

action:
  - variables:
      command: '{{ trigger.event.data.command }}'
  - choose:
      - conditions: >-
          {{ command == 'on_press' }}
        sequence: !input 'on_press'
      - conditions: >-
          {{ command == 'up_press' }}
        sequence: !input 'up_press'
      - conditions: >-
          {{ command == 'down_press' }}
        sequence: !input 'down_press'
      - conditions: >-
          {{ command == 'off_press' }}
        sequence: !input 'off_press'

mode: 'queued'
max_exceeded: 'silent'
