---
blueprint:
  name: 'Hue Dimmer Switch'
  domain: 'automation'
  input:
    remote:
      name: 'Remote'
      selector:
        device:
          integration: 'zha'
          manufacturer: 'Philips'
          model: 'RWL021'
    button_1_single_press:
      name: 'Button 1 (ON) Single Press'
      default: []
      selector:
        action: {}
    button_1_long_press:
      name: 'Button 1 (ON) Long Press'
      default: []
      selector:
        action: {}
    button_1_double_press:
      name: 'Button 1 (ON) Double Press'
      default: []
      selector:
        action: {}
    button_2_single_press:
      name: 'Button 2 (UP) Single Press'
      default: []
      selector:
        action: {}
    button_2_long_press:
      name: 'Button 2 (UP) Long Press'
      default: []
      selector:
        action: {}
    button_2_double_press:
      name: 'Button 2 (UP) Double Press'
      default: []
      selector:
        action: {}
    button_3_single_press:
      name: 'Button 3 (DOWN) Single Press'
      default: []
      selector:
        action: {}
    button_3_long_press:
      name: 'Button 3 (DOWN) Long Press'
      default: []
      selector:
        action: {}
    button_3_double_press:
      name: 'Button 3 (DOWN) Double Press'
      default: []
      selector:
        action: {}
    button_4_single_press:
      name: 'Button 4 (OFF) Single Press'
      default: []
      selector:
        action: {}
    button_4_long_press:
      name: 'Button 4 (OFF) Long Press'
      default: []
      selector:
        action: {}
    button_4_double_press:
      name: 'Button 4 (OFF) Double Press'
      default: []
      selector:
        action: {}

trigger:
  platform: 'event'
  event_type: 'zha_event'
  event_data:
    device_id: !input 'remote'

action:
  - variables:
      command: '{{ trigger.event.data.command }}'
  - choose:
      - conditions: >-
          {{ command == 'on_short_release' }}
        sequence: !input 'button_1_single_press'
      - conditions: >-
          {{ command == 'on_hold' }}
        sequence: !input 'button_1_long_press'
      - conditions: >-
          {{ command == 'on_double_press' }}
        sequence: !input 'button_1_double_press'
      - conditions: >-
          {{ command == 'up_short_release' }}
        sequence: !input 'button_2_single_press'
      - conditions: >-
          {{ command == 'up_hold' }}
        sequence: !input 'button_2_long_press'
      - conditions: >-
          {{ command == 'up_double_press' }}
        sequence: !input 'button_2_double_press'
      - conditions: >-
          {{ command == 'down_short_release' }}
        sequence: !input 'button_3_single_press'
      - conditions: >-
          {{ command == 'down_hold' }}
        sequence: !input 'button_3_long_press'
      - conditions: >-
          {{ command == 'down_double_press' }}
        sequence: !input 'button_3_double_press'
      - conditions: >-
          {{ command == 'off_short_release' }}
        sequence: !input 'button_4_single_press'
      - conditions: >-
          {{ command == 'off_hold' }}
        sequence: !input 'button_4_long_press'
      - conditions: >-
          {{ command == 'off_double_press' }}
        sequence: !input 'button_4_double_press'

mode: 'restart'
max_exceeded: 'silent'
