---
blueprint:
  name: 'Hue Dimmer Switch'
  domain: 'automation'
  input:
    remote:
      name: 'Remote'
      selector:
        text: {}

    on_press:
      name: 'On Press'
      <<: &common_config
        default: []
        selector:
          action: {}
    up_press:
      name: 'Up Press'
      <<: *common_config
    down_press:
      name: 'Down Press'
      <<: *common_config
    off_press:
      name: 'Off Press'
      <<: *common_config

trigger_variables:
  device_friendly_name: !input 'remote'

trigger:
  platform: 'mqtt'
  topic: 'zigbee2mqtt/{{ device_friendly_name }}/action'

action:
  - choose:
      - conditions: '{{ trigger.payload == "on-press" }}'
        sequence: !input 'on_press'
      - conditions: '{{ trigger.payload == "up-press" }}'
        sequence: !input 'up_press'
      - conditions: '{{ trigger.payload == "down-press" }}'
        sequence: !input 'down_press'
      - conditions: '{{ trigger.payload == "off-press" }}'
        sequence: !input 'off_press'

mode: 'queued'
max_exceeded: 'silent'
trace:
  stored_traces: 10
