---
blueprint:
  name: 'Motion-Activated Lights'
  description: >-
    Turn lights on/off based on motion/occupancy and ambient light.

    The targeted lights will turn on when motion/occupancy is detected, unless
    the ambient light level exceeds a configured threshold. The targeted lights
    will turn off when there is an absence of motion/occupancy for a duration
    of `off_delay`.
  domain: 'automation'
  input:
    # TODO: Limit `device_class` to `motion` and `occupancy` sensors.
    trigger_sensor:
      name: 'Motion/Occupancy Sensor'
      selector:
        entity:
          domain: 'binary_sensor'
    light_target:
      name: 'Target Lights'
      selector:
        entity:
          domain: 'light'

    illuminance_sensor:
      name: 'Illuminance Sensor'
      default: []
      selector:
        entity:
          domain: 'sensor'
          device_class: 'illuminance'
    illuminance_threshold:
      name: 'Illuminance Threshold'
      default: 200
      selector:
        number:
          min: 0
          max: 1000
          step: 10
          unit_of_measurement: 'lux'

    off_delay:
      name: 'Off Delay'
      default: 300
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: 'seconds'

trigger:
  platform: 'state'
  entity_id: !input 'trigger_sensor'
  from: 'off'
  to: 'on'

condition:
  - condition: 'numeric_state'
    entity_id: !input 'illuminance_sensor'
    below: !input 'illuminance_threshold'

  # If the target light is already on then it must've been turned on manually.
  #
  # TODO: Add a `force_on` input parameter to bypass this check.
  - condition: 'state'
    entity_id: !input 'light_target'
    state:
      - 'off'
      - 'unavailable'

action:
  - service: 'light.turn_on'
    entity_id: !input 'light_target'
  - wait_for_trigger:
      - platform: 'state'
        entity_id: !input 'trigger_sensor'
        from: 'on'
        to: 'off'
        for: !input 'off_delay'
      - platform: 'state'
        entity_id: !input 'light_target'
        to: 'off'
  - service: 'light.turn_off'
    entity_id: !input 'light_target'

mode: 'single'
max_exceeded: 'silent'
