---
blueprint:
  name: 'Yale Assure Events'
  domain: 'automation'
  input:
    lock:
      name: 'Lock'

      # TODO: Use `device` selector.
      selector:
        text: null

    keypad_unlock:
      name: 'Keypad Unlock'
      <<: &common_config
        default: []
        selector:
          action: null
    manual_lock:
      name: 'Manual Lock'
      <<: *common_config
    manual_unlock:
      name: 'Manual Unlock'
      <<: *common_config
    touch_lock:
      name: 'Touch Lock'
      <<: *common_config
    pin_code_added:
      name: 'PIN Code Added'
      <<: *common_config
    pin_code_deleted:
      name: 'PIN Code Deleted'
      <<: *common_config
    pin_code_changed:
      name: 'PIN Code Changed'
      <<: *common_config
    auto_lock:
      name: 'Auto Lock'
      <<: *common_config

trigger_variables:
  device_friendly_name: !input 'lock'

triggers:
  trigger: 'mqtt'
  topic: 'zigbee2mqtt/{{ device_friendly_name }}'

conditions:
  condition: 'template'
  value_template: >-
    {{ 'action' in trigger.payload_json }}

actions:
  - variables:
      action: '{{ trigger.payload_json.action }}'
      source: '{{ trigger.payload_json.action_source_name }}'
      user: '{{ trigger.payload_json.action_user }}'
  - choose:
      - conditions: '{{ source == "keypad" and action == "unlock" }}'
        sequence: !input 'keypad_unlock'
      - conditions: '{{ source == "manual" and action == "auto_lock" and user == 65535 }}'
        sequence: !input 'auto_lock'
      - conditions: '{{ source == "manual" and action == "manual_lock" and user == 65535 }}'
        sequence: !input 'manual_lock'
      - conditions: '{{ source == "manual" and action == "manual_unlock" and user == 65535 }}'
        sequence: !input 'manual_unlock'
      - conditions: '{{ source == "manual" and action == "one_touch_lock" and user == 65535 }}'
        sequence: !input 'touch_lock'
      - conditions: '{{ action == "pin_code_added" }}'
        sequence: !input 'pin_code_added'
      - conditions: '{{ action == "pin_code_deleted" }}'
        sequence: !input 'pin_code_deleted'
      - conditions: '{{ action == "pin_code_changed" }}'
        sequence: !input 'pin_code_changed'

      # Lock was triggered by Home Assistant.
      - conditions: '{{ source == "rf" and user == 65535 }}'
        sequence: []
    default:
      action: 'system_log.write'
      data:
        message: 'Unexpected event from Yale Assure device: {{ trigger.payload }}'
        level: 'warning'

mode: 'queued'
max_exceeded: 'silent'
trace:
  stored_traces: 20
