---
sensor:
  - platform: 'ade7953_i2c'
    irq_pin: '${irq_pin}'
    voltage:
      name: 'Voltage'
      internal: true
    current_a:
      name: 'Output 2 Current'
      internal: true
    current_b:
      name: 'Output 1 Current'
      internal: true
    active_power_a:
      name: 'Output 2 Power'
      filters:
        lambda: 'return abs(x);'

      # TODO: Move this to a Home Assistant automation.
      on_value_range:
        above: '${max_power}'
        then:
          - output.turn_off: 'output2'
          - homeassistant.service:
              service: 'persistent_notification.create'
              data:
                title: '${device_name} Power Usage'
              data_template:
                message: 'Switch turned off because power exceeded ${max_power}W'
    active_power_b:
      name: 'Output 1 Power'
      filters:
        lambda: 'return abs(x);'

      # TODO: Move this to a Home Assistant automation.
      on_value_range:
        above: '${max_power}'
        then:
          - output.turn_off: 'output1'
          - homeassistant.service:
              service: 'persistent_notification.create'
              data:
                title: '${device_name} Power Usage'
              data_template:
                message: 'Switch turned off because power exceeded ${max_power}W'
    update_interval: '30s'
