---
packages:
  common: !include '../../../packages/common.yaml'
  platform: !include
    file: '../../../packages/platform/esp8266.yaml'
    vars:
      board: 'esp01_1m'
  wifi: !include '../../../packages/wifi.yaml'
