---
substitutions:
  click_min_length: '50ms'
  click_max_length: '350ms'
  hold_min_length: '500ms'
  hold_max_length: '1000ms'

binary_sensor:
  - platform: 'gpio'
    pin: '${pin}'
    id: 'input${id}'
    on_multi_click:
      - timing:
          - 'ON for ${click_min_length} to ${click_max_length}'
        then:
          if:
            condition:
              and:
                - wifi.connected: {}
                - api.connected: {}
            then:
              homeassistant.event:
                event: 'esphome.button'
                data:
                  device: '${device_id}'
                  button: '${id}'
                  action: 'click'
      - timing:
          - 'ON for ${hold_min_length} to ${hold_max_length}'
        then:
          if:
            condition:
              and:
                - wifi.connected: {}
                - api.connected: {}
            then:
              homeassistant.event:
                event: 'esphome.button'
                data:
                  device: '${device_id}'
                  button: '${id}'
                  action: 'hold'
      - timing:
          - 'ON for ${click_min_length} to ${click_max_length}'
          - 'OFF for ${click_min_length} to ${click_max_length}'
          - 'ON for ${click_min_length} to ${click_max_length}'
        then:
          if:
            condition:
              and:
                - wifi.connected: {}
                - api.connected: {}
            then:
              homeassistant.event:
                event: 'esphome.button'
                data:
                  device: '${device_id}'
                  button: '${id}'
                  action: 'double-click'
    internal: true
