---
binary_sensor:
  - platform: 'gpio'
    pin: '${pin}'
    id: 'input${id}'
    on_multi_click:
      - timing:
          - 'ON for ${button_click_min_length} to ${button_click_max_length}'
        then:
          homeassistant.event:
            event: 'esphome.button'
            data:
              device: '${device_id}'
              button: '${id}'
              action: 'click'
      - timing:
          - 'ON for ${button_hold_min_length} to ${button_hold_max_length}'
        then:
          homeassistant.event:
            event: 'esphome.button'
            data:
              device: '${device_id}'
              button: '${id}'
              action: 'hold'
      - timing:
          - 'ON for ${button_click_min_length} to ${button_click_max_length}'
          - 'OFF for ${button_click_min_length} to ${button_click_max_length}'
          - 'ON for ${button_click_min_length} to ${button_click_max_length}'
        then:
          homeassistant.event:
            event: 'esphome.button'
            data:
              device: '${device_id}'
              button: '${id}'
              action: 'double-click'
    internal: true
