---
substitutions:
  component: 'switch'
  platform: 'output'
  name: '${device_name} Output${id}'
  restore_mode: 'ALWAYS_ON'
  internal: 'true'

output:
  - platform: 'gpio'
    pin: '${pin}'
    id: 'output${id}'

${component}:
  - platform: '${platform}'
    output: 'output${id}'
    name: '${name}'
    restore_mode: '${restore_mode}'
    internal: '${internal}'
