---
output:
  - platform: 'gpio'
    pin:
      number: '${pin}'
      ignore_strapping_warning: true
    id: 'output${id}'

switch:
  - platform: 'output'
    output: 'output${id}'
    id: 'switch${id}'
    name: 'Output ${id}'
    restore_mode: 'RESTORE_DEFAULT_ON'
    disabled_by_default: true
