---
sensor:
  - platform: 'adc'
    pin: 'A0'
    id: 'temperature_adc'
  - platform: 'resistance'
    sensor: 'temperature_adc'
    configuration: 'DOWNSTREAM'
    resistor: '32kOhm'
    id: 'temperature_resistance'
  - platform: 'ntc'
    name: 'Temperature'
    sensor: 'temperature_resistance'
    calibration:
      b_constant: 3350
      reference_temperature: '298.15K'
      reference_resistance: '10kOhm'
    accuracy_decimals: 1

    # TODO: Move this to a Home Assistant automation.
    on_value_range:
      above: '${max_temp}'
      then:
        - lambda: !lambda |-
            for (auto *obj : App.get_switches()) {
              if (!obj->is_internal()) {
                obj->turn_off().perform();
              }
            }
        - homeassistant.service:
            service: 'persistent_notification.create'
            data:
              title: '${device_name} Overheated'
            data_template:
              message: 'Switch turned off because temperature exceeded ${max_temp}°C'
