---
id: '7a14e9b0-b1ea-43da-9057-fcd7be8c66c3'
alias: 'Arriving Home'
triggers:
  # TODO: Use https://www.home-assistant.io/docs/automation/trigger/#zone-trigger.
  trigger: 'state'
  entity_id: 'group.family'
  from: 'not_home'
  to: 'home'
conditions:
  condition: 'sun'
  after: 'sunset'

# TODO: Add welcome message (see https://github.com/stanvx/Home-Assistant-Configuration/blob/master/packages/welcome_home.yaml).
actions:
  # Turn some lights on when we arrive home.
  - parallel:
      - action: 'scene.turn_on'
        entity_id: 'scene.arriving_home'

  # Wait for the door to be opened.
  - wait_for_trigger:
      trigger: 'state'
      entity_id: 'binary_sensor.front_door'
      from: 'off'
      to: 'on'
    timeout: 900
    continue_on_timeout: false

  # Turn some lights off after the door is closed.
  - wait_for_trigger:
      trigger: 'state'
      entity_id: 'binary_sensor.front_door'
      from: 'on'
      to: 'off'
    timeout: 300
  - delay: 300
  - action: 'light.turn_off'
    entity_id: 'light.outside_wall'
mode: 'single'
