---
id: 'd66c61c9-1819-4909-bf49-accb40fadfea'
alias: 'Basement Dehumidifier'
trigger:
  platform: 'state'
  entity_id:
    - &basement_humidity 'sensor.basement_humidity'
    - &outside_humidity 'sensor.outside_humidity'
condition:
  condition: 'template'
  value_template: '{{ (as_timestamp(now()) - as_timestamp(state_attr("automation.basement_dehumidifier", "last_triggered")) | int(0)) > 1800 }}'
action:
  choose:
    - conditions:
        condition: 'numeric_state'
        entity_id: *basement_humidity
        below: 40
      sequence:
        service: 'switch.turn_off'
        entity_id:
          - &primary_dehumidifier 'switch.basement_primary_dehumidifier'
          - &secondary_dehumidifier 'switch.basement_secondary_dehumidifier'
    - conditions:
        condition: 'numeric_state'
        entity_id: *basement_humidity
        above: 80
      sequence:
        service: 'switch.turn_on'
        entity_id:
          - *primary_dehumidifier
          - *secondary_dehumidifier
    - conditions:
        condition: 'numeric_state'
        entity_id: *basement_humidity
        above: *outside_humidity
      sequence:
        - service: 'switch.turn_on'
          entity_id: *primary_dehumidifier
        - service: 'switch.turn_off'
          entity_id: *secondary_dehumidifier
    - conditions:
        condition: 'numeric_state'
        entity_id: *basement_humidity
        below: *outside_humidity
      sequence:
        - service: 'switch.turn_off'
          entity_id:
            - *primary_dehumidifier
            - *secondary_dehumidifier
mode: 'single'
max_exceeded: 'silent'
trace:
  stored_traces: 20
