---
id: 'bc91c7b0-9a04-4d7c-8d11-2c0d6173e9fd'
alias: 'Bathroom Fan'
trigger:
  - platform: 'template'
    id: 'high_humidity'
    value_template: '{{ states("sensor.bathroom_humidity") | float >= states("sensor.toilet_humidity") | float + 5 }}'
  - platform: 'template'
    id: 'low_humidity'
    value_template: '{{ states("sensor.bathroom_humidity") | float < states("sensor.toilet_humidity") | float + 3 }}'
    for: 600
action:
  choose:
    - conditions:
        condition: 'trigger'
        id: 'high_humidity'
      sequence:
        service: 'fan.turn_on'
        target:
          entity_id: 'fan.bathroom'
    - conditions:
        condition: 'trigger'
        id: 'low_humidity'
      sequence:
        service: 'fan.turn_off'
        target:
          entity_id: 'fan.bathroom'
