---
id: 'bc91c7b0-9a04-4d7c-8d11-2c0d6173e9fd'
alias: 'Bathroom Fan'
trigger:
  - platform: 'template'
    value_template: &high_humidity >-
      {{ states('sensor.bathroom_humidity') | float >= states('sensor.toilet_humidity') | float + 5 }}
  - platform: 'template'
    value_template: &low_humidity >-
      {{ states('sensor.bathroom_humidity') | float < states('sensor.toilet_humidity') | float + 3 }}
    for: 600
action:
  choose:
    - conditions: *high_humidity
      sequence:
        - service: 'fan.turn_on'
          target:
            entity_id: 'fan.bathroom'
    - conditions: *low_humidity
      sequence:
        - service: 'fan.turn_off'
          target:
            entity_id: 'fan.bathroom'
