---
id: '31c797b8-4353-4bd6-b4b8-d185c6e963f0'
alias: 'Day Lighting'
triggers:
  trigger: 'sun'
  event: 'sunrise'
actions:
  - scene: 'scene.day_time'

  # TODO: Remove this hack.
  - action: 'light.turn_on'
    target:
      entity_id:
        - 'light.hallway'
        - 'light.toilet'
    data:
      brightness: 255
  - action: 'light.turn_off'
    target:
      entity_id:
        - 'light.hallway'
        - 'light.toilet'
