---
id: '31c797b8-4353-4bd6-b4b8-d185c6e963f0'
alias: 'Day Lighting'
trigger:
  platform: 'sun'
  event: 'sunrise'
action:
  - scene: 'scene.day_time'

  # TODO: Remove this hack.
  - service: 'light.turn_on'
    target:
      entity_id: 'light.toilet'
    data:
      brightness: 255
  - service: 'light.turn_off'
    target:
      entity_id: 'light.toilet'
