---
id: '4f1d6cb3-b8fb-42d1-a0fc-b90eee1bf7a5'
alias: 'Mail Delivery'
trigger:
  platform: 'state'
  entity_id: 'binary_sensor.mailbox_top_door'
  from: 'off'
  to: 'on'
condition:
  condition: 'time'
  after: '08:00:00'
  before: '18:00:00'
  weekday:
    - 'mon'
    - 'tue'
    - 'wed'
    - 'thu'
    - 'fri'
action:
  service: 'notify.mobile_app_josh_phone'
  data:
    title: 'Mailbox Activity'
    message: 'Mailbox door was opened.'
