---
id: '9383a9d8-4bdf-4021-9629-0ca2aea5eabe'
alias: 'Theme Selection'
description: 'Automatically change the default frontend theme.'
trigger:
  platform: 'state'
  entity_id: 'sun.sun'
action:
  service: 'frontend.set_theme'
  data:
    name: >-
      {% if is_state('sun.sun', 'above_horizon') %}
        default
      {% elif is_state('sun.sun', 'below_horizon') %}
        slate
      {% endif %}
