---
id: '116e3a13-2dfa-4199-9fcb-982d1f6708da'
alias: 'Turn Off TV'
trigger:
  platform: 'state'
  entity_id: 'media_player.living_room_tv'
  to: 'standby'
  for: 60
action:
  service: 'media_player.turn_off'
  entity_id: 'media_player.living_room_tv'
