# yamllint disable rule:key-ordering rule:line-length rule:quoted-strings
---
alias: 'Update Available Notification'
trigger:
  - platform: 'state'
    entity_id: 'binary_sensor.updater'
    from: 'off'
    to: 'on'
action:
  - service: 'persistent_notification.create'
    data:
      title: 'Update Available'
      message: "Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version') }} is available."
