---
alias: 'Stop vacuum'
id: 'a9f98a0e-8480-48c2-95c1-d4cec145b32a'
trigger:
  platform: 'state'
  entity_id: 'group.family'
  to: 'home'
action:
  service: 'vacuum.return_to_base'
  entity_id: 'vacuum.deebot'
mode: 'single'
