---
alias: 'Start vacuum'
id: '01119384-ba58-4ae6-8cfc-1c32708691ba'
trigger:
  - platform: 'state'
    entity_id: 'group.family'
    to: 'home'
  - platform: 'time'
    at: '13:00'
action:
  service: 'vacuum.start'
  entity_id: 'vacuum.deebot'
mode: 'single'
