---
id: 'a7e693d8-45df-4f2a-85e4-b0fa7cf6a682'
alias: 'Water Leak'
trigger:
  platform: 'state'
  entity_id:
    - 'binary_sensor.dishwasher_water_leak'
    - 'binary_sensor.kitchen_sink_water_leak'
    - 'binary_sensor.spa_bath_water_leak'
  from: 'off'
  to: 'on'
action:
  service: 'script.mobile_app_notify'
  data:
    target: 'josh_phone'
    title: 'Water leak'
    message: 'Water leak detected in {{ trigger.to_state.friendly_name }}.'
    tag: 'water-leak'
trace:
  stored_traces: 20
