---
alias: 'Zoom Do Not Disturb'
id: 'adb46aca-b371-4216-812b-a536325735f2'
trigger:
  platform: 'state'
  entity_id: &entity_id 'binary_sensor.zoom_atlassian'
variables:
  data: >-
    {% if states("binary_sensor.zoom_atlassian") == "on" %}
      priority_only
    {% else %}
      off
    {% endif %}
action:
  service: 'script.mobile_app_command'
  data:
    device: 'josh_phone'
    command: 'command_dnd'
    data: '{{ data }}'
