---
substitutions:
  device_board: 'esp32dev'

packages:
  platform: !include '../packages/platform/esp32.yaml'
  wifi: !include '../packages/wifi.yaml'

esphome:
  on_boot:
    then:
      button.press: 'wakeup'

uart:
  baud_rate: 9600
  tx_pin: 'GPIO16'
  rx_pin: 'GPIO17'

status_led:
  pin: 'GPIO23'

external_components:
  - source: 'github://tjhorner/esphome-standing-desk'

sensor:
  - platform: 'internal_temperature'
    name: 'Internal Temperature'
  - platform: 'standing_desk_height'
    id: 'desk_height'
    name: 'Desk Height'
    unit_of_measurement: 'cm'
    device_class: 'distance'
    variant: '${variant}'

output:
  - platform: 'gpio'
    pin: 'GPIO21'
    id: 'desk_up'
    inverted: true
  - platform: 'gpio'
    pin: 'GPIO22'
    id: 'desk_down'
    inverted: true

  - platform: 'gpio'
    pin: 'GPIO21'
    id: 'button_bit1'
    inverted: true
  - platform: 'gpio'
    pin: 'GPIO22'
    id: 'button_bit2'
    inverted: true
  - platform: 'gpio'
    pin: 'GPIO19'
    id: 'button_bit4'
    inverted: true
  - platform: 'gpio'
    pin: 'GPIO18'
    id: 'button_m'
    inverted: true

number:
  - platform: 'template'
    id: 'target_height'
    name: 'Target Desk Height'
    unit_of_measurement: 'cm'
    device_class: 'distance'
    min_value: 70.0
    max_value: 125.0
    step: 0.1
    optimistic: true
    restore_value: true
    set_action:
      then:
        if:
          condition:
            lambda: |-
              return id(desk_height)->get_last_read() > x;
          then:
            - output.turn_on: 'desk_down'
            - wait_until:
                condition:
                  lambda: |-
                    return id(desk_height)->get_last_read() <= x + 0.4;
                timeout: '20s'
            - output.turn_off: 'desk_down'
          else:
            - output.turn_on: 'desk_up'
            - wait_until:
                condition:
                  lambda: |-
                    return id(desk_height)->get_last_read() >= x - 0.4;
                timeout: '20s'
            - output.turn_off: 'desk_up'

button:
  # Recall presets.
  - platform: 'template'
    id: 'recall_preset_1'
    name: 'Preset 1'
    icon: 'mdi:numeric-1-box'
    on_press:
      - output.turn_on: 'button_bit1'
      - output.turn_on: 'button_bit2'
      - delay: '1s'
      - output.turn_off: 'button_bit2'
      - output.turn_off: 'button_bit1'
  - platform: 'template'
    id: 'recall_preset_2'
    name: 'Preset 2'
    icon: 'mdi:numeric-2-box'
    on_press:
      - output.turn_on: 'button_bit4'
      - delay: '100ms'
      - output.turn_off: 'button_bit4'
  - platform: 'template'
    id: 'recall_preset_3'
    name: 'Preset 3'
    icon: 'mdi:numeric-3-box'
    on_press:
      - output.turn_on: 'button_bit2'
      - output.turn_on: 'button_bit4'
      - delay: '100ms'
      - output.turn_off: 'button_bit4'
      - output.turn_off: 'button_bit2'
  - platform: 'template'
    id: 'recall_preset_4'
    name: 'Preset 4'
    icon: 'mdi:numeric-4-box'
    on_press:
      - output.turn_on: 'button_bit4'
      - output.turn_on: 'button_bit1'
      - delay: '100ms'
      - output.turn_off: 'button_bit1'
      - output.turn_off: 'button_bit4'

  # Set presets.
  - platform: 'template'
    name: 'Set Preset 1'
    icon: 'mdi:numeric-1-box-multiple'
    disabled_by_default: true
    entity_category: 'config'
    on_press:
      - output.turn_on: 'button_m'
      - delay: '100ms'
      - output.turn_off: 'button_m'
      - button.press: 'recall_preset_1'
  - platform: 'template'
    name: 'Set Preset 2'
    icon: 'mdi:numeric-2-box-multiple'
    disabled_by_default: true
    entity_category: 'config'
    on_press:
      - output.turn_on: 'button_m'
      - delay: '100ms'
      - output.turn_off: 'button_m'
      - button.press: 'recall_preset_2'
  - platform: 'template'
    name: 'Set Preset 3'
    icon: 'mdi:numeric-3-box-multiple'
    disabled_by_default: true
    entity_category: 'config'
    on_press:
      - output.turn_on: 'button_m'
      - delay: '100ms'
      - output.turn_off: 'button_m'
      - button.press: 'recall_preset_3'
  - platform: 'template'
    name: 'Set Preset 4'
    icon: 'mdi:numeric-4-box-multiple'
    disabled_by_default: true
    entity_category: 'config'
    on_press:
      - output.turn_on: 'button_m'
      - delay: '100ms'
      - output.turn_off: 'button_m'
      - button.press: 'recall_preset_4'

  - platform: 'template'
    name: 'Wakeup'
    id: 'wakeup'
    icon: 'mdi:cog-refresh'
    disabled_by_default: true
    entity_category: 'config'
    on_press:
      uart.write:
        - 0x00
