# Based on https://www.esphome-devices.com/devices/Shelly-1.
---
packages:
  common: !include 'packages/common.yaml'

  input1: !include
    file: 'packages/input.yaml'
    vars:
      id: 1
      pin: 'GPIO5'

  output1: !include
    file: 'packages/output.yaml'
    vars:
      id: 1
      pin: 'GPIO4'
