# Based on https://www.esphome-devices.com/devices/Shelly-1.
---
substitutions:
  input1_gpio: 'GPIO5'
  output1_gpio: 'GPIO4'

packages:
  common: !include 'common.yaml'

binary_sensor:
  - platform: 'gpio'
    pin: '${input1_gpio}'
    id: 'input1'
    on_multi_click:
      - timing:
          - 'ON for ${button_click_min_length} to ${button_click_max_length}'
        then:
          homeassistant.event:
            event: &button_event 'esphome.button'
            data:
              device: '${device_name}'
              button: '1'
              action: 'click'
      - timing:
          - 'ON for ${button_hold_min_length} to ${button_hold_max_length}'
        then:
          homeassistant.event:
            event: *button_event
            data:
              device: '${device_name}'
              button: '1'
              action: 'hold'
      - timing:
          - 'ON for ${button_click_min_length} to ${button_click_max_length}'
          - 'OFF for ${button_click_min_length} to ${button_click_max_length}'
          - 'ON for ${button_click_min_length} to ${button_click_max_length}'
        then:
          homeassistant.event:
            event: *button_event
            data:
              device: '${device_name}'
              button: '1'
              action: 'double-click'
    internal: true
