# Based on https://www.esphome-devices.com/devices/Shelly-1.
---
substitutions:
  input1_gpio: 'GPIO5'
  output1_gpio: 'GPIO4'

packages:
  common: !include 'common.yaml'
  input1: !include 'packages/input1.yaml'
  output1: !include 'packages/output1.yaml'
