# Based on https://www.esphome-devices.com/devices/Shelly-1.
---
substitutions:
  input1_gpio: 'GPIO5'
  output1_gpio: 'GPIO4'

packages:
  common: !include 'common.yaml'

binary_sensor:
  - !include 'components/input1.yaml'

output:
  - platform: 'gpio'
    pin: '${output1_gpio}'
    id: 'relay1'
