# Based on https://www.esphome-devices.com/devices/Shelly-1L.
---
substitutions:
  input1_gpio: 'GPIO4'
  input2_gpio: 'GPIO14'
  output1_gpio: 'GPIO5'

packages:
  common: !include 'common.yaml'
  input1: !include 'packages/input1.yaml'
  input2: !include 'packages/input2.yaml'
  output1: !include 'packages/output1.yaml'
  temperature: !include 'packages/temperature.yaml'

status_led:
  pin:
    number: 'GPIO0'
