# Based on https://www.esphome-devices.com/devices/Shelly-1L.
---
substitutions:
  input1_gpio: 'GPIO4'
  input2_gpio: 'GPIO14'
  output1_gpio: 'GPIO5'

packages:
  common: !include 'common.yaml'

sensor:
  # Temperature
  - platform: 'adc'
    pin: 'A0'
    id: 'temperature_adc'
  - platform: 'resistance'
    sensor: 'temperature_adc'
    configuration: 'DOWNSTREAM'
    resistor: '32kOhm'
    id: 'temperature_resistance'
  - platform: 'ntc'
    name: '${device_name} Temperature'
    sensor: 'temperature_resistance'
    calibration:
      b_constant: 3350
      reference_temperature: '298.15K'
      reference_resistance: '10kOhm'
    accuracy_decimals: 1

    # TODO: Move this to a Home Assistant automation.
    on_value_range:
      above: '${max_temp}'
      then:
        - output.turn_off: 'relay1'
        - homeassistant.service:
            service: 'persistent_notification.create'
            data:
              title: '${device_name} Overheated'
            data_template:
              message: 'Switch turned off because temperature exceeded ${max_temp}°C'

status_led:
  pin:
    number: 'GPIO0'

binary_sensor:
  - !include 'components/input1.yaml'
  - !include 'components/input2.yaml'

output:
  - platform: 'gpio'
    pin: '${output1_gpio}'
    id: 'relay1'
