# Based on https://www.esphome-devices.com/devices/Shelly-1L.
---
substitutions:
  input1_gpio: 'GPIO4'
  input2_gpio: 'GPIO14'
  output1_gpio: 'GPIO5'

packages:
  common: !include 'common.yaml'

sensor:
  # Temperature
  - platform: 'adc'
    pin: 'A0'
    id: 'temperature_adc'
  - platform: 'resistance'
    sensor: 'temperature_adc'
    configuration: 'DOWNSTREAM'
    resistor: '32kOhm'
    id: 'temperature_resistance'
  - platform: 'ntc'
    name: '${device_name} Temperature'
    sensor: 'temperature_resistance'
    calibration:
      b_constant: 3350
      reference_temperature: '298.15K'
      reference_resistance: '10kOhm'
    accuracy_decimals: 1

    # TODO: Move this to a Home Assistant automation.
    on_value_range:
      above: '${max_temp}'
      then:
        - output.turn_off: 'relay1'
        - homeassistant.service:
            service: 'persistent_notification.create'
            data:
              title: '${device_name} Overheated'
            data_template:
              message: 'Switch turned off because temperature exceeded ${max_temp}°C'

status_led:
  pin:
    number: 'GPIO0'

binary_sensor:
  - platform: 'gpio'
    pin: '${input1_gpio}'
    id: 'input1'
    on_multi_click:
      - timing:
          - 'ON for ${button_click_min_length} to ${button_click_max_length}'
        then:
          homeassistant.event:
            event: &button_event 'esphome.button'
            data:
              device: '${device_name}'
              button: '1'
              action: 'click'
      - timing:
          - 'ON for ${button_hold_min_length} to ${button_hold_max_length}'
        then:
          homeassistant.event:
            event: *button_event
            data:
              device: '${device_name}'
              button: '1'
              action: 'hold'
      - timing:
          - 'ON for ${button_click_min_length} to ${button_click_max_length}'
          - 'OFF for ${button_click_min_length} to ${button_click_max_length}'
          - 'ON for ${button_click_min_length} to ${button_click_max_length}'
        then:
          homeassistant.event:
            event: *button_event
            data:
              device: '${device_name}'
              button: '1'
              action: 'double-click'
    internal: true
  - platform: 'gpio'
    pin: '${input2_gpio}'
    id: 'input2'
    on_multi_click:
      - timing:
          - 'ON for ${button_click_min_length} to ${button_click_max_length}'
        then:
          homeassistant.event:
            event: *button_event
            data:
              device: '${device_name}'
              button: '2'
              action: 'click'
      - timing:
          - 'ON for ${button_hold_min_length} to ${button_hold_max_length}'
        then:
          homeassistant.event:
            event: *button_event
            data:
              device: '${device_name}'
              button: '2'
              action: 'hold'
      - timing:
          - 'ON for ${button_click_min_length} to ${button_click_max_length}'
          - 'OFF for ${button_click_min_length} to ${button_click_max_length}'
          - 'ON for ${button_click_min_length} to ${button_click_max_length}'
        then:
          homeassistant.event:
            event: *button_event
            data:
              device: '${device_name}'
              button: '2'
              action: 'double-click'
    internal: true
