# Based on https://www.esphome-devices.com/devices/Shelly-1L.
---
substitutions:
  status_led_inverted: 'false'

packages:
  common: !include 'packages/common.yaml'
  input1: !include
    file: 'packages/input.yaml'
    vars:
      id: '1'
      pin: 'GPIO4'
  input2: !include
    file: 'packages/input.yaml'
    vars:
      id: '2'
      pin: 'GPIO14'
  output1: !include
    file: 'packages/output.yaml'
    vars:
      id: '1'
      pin: 'GPIO5'
      component: '${output1_component}'
      platform: '${output1_platform}'
      name: '${output1_name}'
      restore_mode: '${output1_restore_mode}'
      internal: '${output1_internal}'
  status_led: !include 'packages/status_led.yaml'
  temperature: !include 'packages/temperature.yaml'
