# Based on https://www.esphome-devices.com/devices/Shelly-1PM.
---
substitutions:
  input1_gpio: 'GPIO4'
  output1_gpio: 'GPIO15'

packages:
  common: !include 'common.yaml'
  input1: !include 'packages/input1.yaml'
  output1: !include 'packages/output1.yaml'
  temperature: !include 'packages/temperature.yaml'

sensor:
  # Power Monitoring
  - platform: 'hlw8012'
    cf_pin: 'GPIO5'
    power:
      name: '${device_name} Power'
      unit_of_measurement: 'W'
      device_class: 'power'
      state_class: 'measurement'
      accuracy_decimals: 0
      filters:
        - calibrate_linear:
            - '0.0 -> 1.0'
            - '110.33186 -> 20.62'
            - '131.01909 -> 24.32'
            - '341.33920 -> 62.08'
            - '5561.41553 -> 1000.0'
            - '2975.51221 -> 535.7'
            - '9612.66309 -> 1720.0'
            - '14891.35352 -> 2679.0'

        # Make everything below 2W appear as just 0W.
        - lambda: 'if (x < 2) return 0; else return x;'
    update_interval: '10s'

    # These are not used because it is not available on the 1PM but it is needed to compile.
    sel_pin: 'GPIO14'
    cf1_pin: 'GPIO13'

output:
  - platform: 'esp8266_pwm'
    id: 'state_led'
    pin:
      number: 'GPIO0'
      inverted: true
