# Based on https://devices.esphome.io/devices/Shelly-1PM.
---
packages:
  common: !include 'packages/common.yaml'
  platform: !include
    file: '../../packages/platform/esp8266.yaml'
    vars:
      board: 'esp01_1m'

  status_led: !include 'packages/status_led.yaml'
  temperature: !include
    file: 'packages/temperature.yaml'
    vars:
      adc_pin: 'A0'
      resistor: '32kOhm'
  temperature_esp8266:
    sensor:
      - id: !extend 'temperature_adc'
        attenuation: !remove

  input1: !include
    file: 'packages/input.yaml'
    vars:
      id: 1
      pin: 'GPIO4'

  output1: !include
    file: 'packages/output.yaml'
    vars:
      id: 1
      pin: 'GPIO15'

sensor:
  - platform: 'hlw8012'
    sel_pin: 'GPIO14'
    cf_pin: 'GPIO5'
    cf1_pin: 'GPIO13'
    power:
      name: 'Power'
      device_class: 'power'
      filters:
        - calibrate_linear:
            - '0.0 -> 1.0'
            - '110.33186 -> 20.62'
            - '131.01909 -> 24.32'
            - '341.33920 -> 62.08'
            - '5561.41553 -> 1000.0'
            - '2975.51221 -> 535.7'
            - '9612.66309 -> 1720.0'
            - '14891.35352 -> 2679.0'

        # Make everything below 2W appear as just 0W.
        - lambda: 'if (x < 2) return 0; else return x;'
    update_interval: '10s'
