# Based on https://www.esphome-devices.com/devices/Shelly-25.
---
substitutions:
  input1_gpio: 'GPIO13'
  input2_gpio: 'GPIO5'
  output1_gpio: 'GPIO4'
  output2_gpio: 'GPIO15'

packages:
  common: !include 'packages/common.yaml'
  input1: !include 'packages/input1.yaml'
  input2: !include 'packages/input2.yaml'
  output1: !include 'packages/output1.yaml'
  output2: !include 'packages/output2.yaml'
  status_led: !include 'packages/status_led.yaml'
  temperature: !include 'packages/temperature.yaml'

i2c:
  sda: 'GPIO12'
  scl: 'GPIO14'

sensor:
  # Power Monitoring
  - platform: 'ade7953'
    irq_pin: 'GPIO16'
    voltage:
      name: '${device_name} Voltage'
      internal: true
    current_a:
      name: '${device_name} Output2 Current'
      internal: true
    current_b:
      name: '${device_name} Output1 Current'
      internal: true
    active_power_a:
      name: '${device_name} Output2 Power'

      # TODO: Move this to a Home Assistant automation.
      on_value_range:
        above: '${max_power}'
        then:
          - output.turn_off: 'output2'
          - homeassistant.service:
              service: 'persistent_notification.create'
              data:
                title: '${device_name} Power Usage'
              data_template:
                message: 'Switch turned off because power exceeded ${max_power}W'
    active_power_b:
      name: '${device_name} Output1 Power'
      filters:
        multiply: -1

      # TODO: Move this to a Home Assistant automation.
      on_value_range:
        above: '${max_power}'
        then:
          - output.turn_off: 'output1'
          - homeassistant.service:
              service: 'persistent_notification.create'
              data:
                title: '${device_name} Power Usage'
              data_template:
                message: 'Switch turned off because power exceeded ${max_power}W'
    update_interval: '30s'
