# Based on https://devices.esphome.io/devices/Shelly-25.
---
substitutions:
  max_power: '2000.0'

packages:
  common: !include 'packages/common.yaml'
  platform: !include
    file: '../../packages/platform/esp8266.yaml'
    vars:
      board: 'esp01_1m'

  i2c: !include 'packages/i2c.yaml'
  status_led: !include 'packages/status_led.yaml'
  temperature: !include
    file: 'packages/temperature.yaml'
    vars:
      max_temp: 90.0

  input1: !include
    file: 'packages/input.yaml'
    vars:
      id: 1
      pin: 'GPIO13'
  input2: !include
    file: 'packages/input.yaml'
    vars:
      id: 2
      pin: 'GPIO5'

  output1: !include
    file: 'packages/output.yaml'
    vars:
      id: 1
      pin: 'GPIO4'
  output2: !include
    file: 'packages/output.yaml'
    vars:
      id: 2
      pin: 'GPIO15'

# Power monitoring
# TODO: Move this to a package.
sensor:
  - platform: 'ade7953_i2c'
    irq_pin: 'GPIO16'
    voltage:
      name: 'Voltage'
      internal: true
    current_a:
      name: 'Output 2 Current'
      internal: true
    current_b:
      name: 'Output 1 Current'
      internal: true
    active_power_a:
      name: 'Output 2 Power'

      # TODO: Move this to a Home Assistant automation.
      on_value_range:
        above: '${max_power}'
        then:
          - output.turn_off: 'output2'
          - homeassistant.service:
              service: 'persistent_notification.create'
              data:
                title: '${device_name} Power Usage'
              data_template:
                message: 'Switch turned off because power exceeded ${max_power}W'
    active_power_b:
      name: 'Output 1 Power'
      filters:
        lambda: 'return abs(x);'

      # TODO: Move this to a Home Assistant automation.
      on_value_range:
        above: '${max_power}'
        then:
          - output.turn_off: 'output1'
          - homeassistant.service:
              service: 'persistent_notification.create'
              data:
                title: '${device_name} Power Usage'
              data_template:
                message: 'Switch turned off because power exceeded ${max_power}W'
    update_interval: '30s'
