# Based on https://www.esphome-devices.com/devices/Shelly-25.
---
packages:
  common: !include 'packages/common.yaml'
  input1: !include
    file: 'packages/input.yaml'
    vars:
      id: '1'
      pin: 'GPIO13'
  input2: !include
    file: 'packages/input.yaml'
    vars:
      id: '2'
      pin: 'GPIO5'
  output1: !include
    file: 'packages/output.yaml'
    vars:
      id: '1'
      pin: 'GPIO4'
      component: '${output1_component}'
      platform: '${output1_platform}'
      name: '${output1_name}'
      restore_mode: '${output1_restore_mode}'
      internal: '${output1_internal}'
  output2: !include
    file: 'packages/output.yaml'
    vars:
      id: '2'
      pin: 'GPIO15'
      component: '${output2_component}'
      platform: '${output2_platform}'
      name: '${output2_name}'
      restore_mode: '${output2_restore_mode}'
      internal: '${output2_internal}'
  status_led: !include 'packages/status_led.yaml'
  temperature: !include 'packages/temperature.yaml'

i2c:
  sda: 'GPIO12'
  scl: 'GPIO14'

sensor:
  # Power Monitoring
  - platform: 'ade7953'
    irq_pin: 'GPIO16'
    voltage:
      name: 'Voltage'
      internal: true
    current_a:
      name: 'Output2 Current'
      internal: true
    current_b:
      name: 'Output1 Current'
      internal: true
    active_power_a:
      name: 'Output2 Power'

      # TODO: Move this to a Home Assistant automation.
      on_value_range:
        above: '${max_power}'
        then:
          - output.turn_off: 'output2'
          - homeassistant.service:
              service: 'persistent_notification.create'
              data:
                title: '${device_name} Power Usage'
              data_template:
                message: 'Switch turned off because power exceeded ${max_power}W'
    active_power_b:
      name: 'Output1 Power'
      filters:
        lambda: 'return abs(x);'

      # TODO: Move this to a Home Assistant automation.
      on_value_range:
        above: '${max_power}'
        then:
          - output.turn_off: 'output1'
          - homeassistant.service:
              service: 'persistent_notification.create'
              data:
                title: '${device_name} Power Usage'
              data_template:
                message: 'Switch turned off because power exceeded ${max_power}W'
    update_interval: '30s'
