# Based on https://devices.esphome.io/devices/Shelly-25.
---
packages:
  common: !include 'packages/common.yaml'
  platform: !include
    file: '../../packages/platform/esp8266.yaml'
    vars:
      board: 'esp01_1m'

  ade7953: !include
    file: 'packages/ade7953.yaml'
    vars:
      irq_pin: 'GPIO16'
  i2c: !include
    file: 'packages/i2c.yaml'
    vars:
      sda: 'GPIO12'
      scl: 'GPIO14'
  status_led: !include 'packages/status_led.yaml'
  temperature: !include
    file: 'packages/temperature.yaml'
    vars:
      adc_pin: 'A0'
      resistor: '32kOhm'
  temperature_esp8266:
    sensor:
      - id: !extend 'temperature_adc'
        attenuation: !remove

  input1: !include
    file: 'packages/input.yaml'
    vars:
      id: 1
      pin: 'GPIO13'
  input2: !include
    file: 'packages/input.yaml'
    vars:
      id: 2
      pin: 'GPIO5'

  output1: !include
    file: 'packages/output.yaml'
    vars:
      id: 1
      pin: 'GPIO4'
  output2: !include
    file: 'packages/output.yaml'
    vars:
      id: 2
      pin: 'GPIO15'
