---
substitutions:
  button_click_min_length: '50ms'
  button_click_max_length: '350ms'
  button_hold_min_length: '500ms'
  button_hold_max_length: '1000ms'
  device_board: 'esp01_1m'
  device_platform: 'esp8266'
  max_power: '2000.0'
  max_temp: '90.0'

  # NOTE: See esphome/issues#1532.
  wifi_power_save_mode: 'high'

packages:
  wifi: !include '../../packages/wifi.yaml'

external_components:
  # TODO: Remove this after the 2022.1 release.
  - source: 'github://esphome/esphome@dev'
    components:
      - 'output'

  # TODO: Remove this after esphome/esphome#3051 has been merged and released.
  - source: 'github://joshuaspence/esphome@fan-restore_mode'
    components:
      - 'fan'
