---
substitutions:
  device_board: 'esp01_1m'
  device_platform: 'ESP8266'
  max_power: '2000.0'
  max_temp: '80.0'

  # NOTE: See esphome/issues#1532.
  wifi_power_save_mode: 'high'

packages:
  wifi: !include '../../packages/wifi.yaml'
