# Based on https://devices.esphome.io/devices/Shelly-1.
---
packages:
  common: !include 'packages/common.yaml'
  platform: !include
    file: '../../packages/platform/esp32.yaml'
    vars:
      board: 'esp32doit-devkit-v1'

  status_led: !include 'packages/status_led.yaml'
  temperature: !include 'packages/temperature.yaml'

  input1: !include
    file: 'packages/input.yaml'
    vars:
      id: 1
      pin: 'GPIO4'

  output1: !include
    file: 'packages/output.yaml'
    vars:
      id: 1
      pin: 'GPIO26'

esphome:
  platformio_options:
    board_build.f_cpu: '160000000L'

esp32:
  framework:
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: 'y'
      CONFIG_ESP32_DEFAULT_CPU_FREQ_160: 'y'
      CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: '160'

# TODO: Refactor this.
sensor:
  - id: !extend 'temperature_adc'
    pin: 'GPIO32'
    attenuation: '11db'
  - id: !extend 'temperature_resistance'
    resistor: '10kOhm'
