# Based on https://devices.esphome.io/devices/Shelly-Plus-1PM.
---
packages:
  common: !include 'packages/common.yaml'
  platform: !include
    file: '../../packages/platform/esp32.yaml'
    vars:
      board: 'esp32doit-devkit-v1'

  status_led: !include 'packages/status_led.yaml'
  temperature: !include
    file: 'packages/temperature.yaml'
    vars:
      adc_attenuation: '11db'
      adc_pin: 'GPIO32'
      resistor: '10kOhm'

  input1: !include
    file: 'packages/input.yaml'
    vars:
      id: 1
      pin: 'GPIO4'

  output1: !include
    file: 'packages/output.yaml'
    vars:
      id: 1
      pin: 'GPIO26'

esphome:
  platformio_options:
    board_build.f_cpu: '160000000L'

esp32:
  framework:
    sdkconfig_options:
      CONFIG_ESP32_DEFAULT_CPU_FREQ_160: 'y'
      CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: '160'
      CONFIG_FREERTOS_UNICORE: 'y'

binary_sensor:
  - platform: 'gpio'
    pin:
      number: 'GPIO25'
      inverted: true
      mode:
        input: true
        pullup: true
    id: 'button1'
    internal: true
    filters:
      delayed_on_off: '5s'
    on_press:
      then:
        button.press: 'button_restart'
