# Based on https://devices.esphome.io/devices/Shelly-Plus-2PM.
---
packages:
  common: !include 'packages/common.yaml'
  platform: !include
    file: '../../packages/platform/esp32.yaml'
    vars:
      board: 'esp32doit-devkit-v1'

  status_led: !include 'packages/status_led.yaml'

  input1: !include
    file: 'packages/input.yaml'
    vars:
      id: 1
      pin: 'GPIO5'
  input2: !include
    file: 'packages/input.yaml'
    vars:
      id: 2
      pin: 'GPIO18'

  output1: !include
    file: 'packages/output.yaml'
    vars:
      id: 1
      pin: 'GPIO12'
  output2: !include
    file: 'packages/output.yaml'
    vars:
      id: 2
      pin: 'GPIO13'

binary_sensor:
  - platform: 'gpio'
    pin:
      number: 'GPIO4'
      inverted: true
      mode:
        input: true
        pullup: true
    id: 'button1'
    internal: true
    filters:
      delayed_on_off: '5s'
    on_press:
      then:
        button.press: 'button_restart'

i2c:
  sda: 'GPIO26'
  scl: 'GPIO25'
