# Based on https://devices.esphome.io/devices/Shelly-Plus-1PM.
---
<<: !include 'plus1.yaml'

sensor:
  - platform: 'hlw8012'
    sel_pin:
      number: 'GPIO23'
      inverted: true
    cf_pin:
      number: 'GPIO5'
      ignore_strapping_warning: true
    cf1_pin: 'GPIO18'
    current:
      name: 'Current'
      device_class: 'current'
      accuracy_decimals: 3
      internal: true
    power:
      name: 'Power'
      device_class: 'power'
    voltage:
      name: 'Voltage'
      device_class: 'voltage'
      accuracy_decimals: 1
      internal: true
    update_interval: '10s'
    current_resistor: 0.001
    voltage_divider: 1925
    model: 'BL0937'
    change_mode_every: 2
