# Based on https://devices.esphome.io/devices/Shelly-Plus-2PM.
---
packages:
  common: !include 'packages/common.yaml'
  platform: !include
    file: '../../packages/platform/esp32.yaml'
    vars:
      board: 'esp32doit-devkit-v1'

  ade7953: !include
    file: 'packages/ade7953.yaml'
    vars:
      irq_pin: 'GPIO27'
  i2c: !include
    file: 'packages/i2c.yaml'
    vars:
      sda: 'GPIO26'
      scl: 'GPIO25'
  status_led: !include 'packages/status_led.yaml'
  temperature: !include
    file: 'packages/temperature.yaml'
    vars:
      adc_attenuation: '12db'
      adc_pin: 'GPIO35'
      resistor: '10kOhm'

  button1: !include
    file: 'packages/button.yaml'
    vars:
      id: 1
      pin: 'GPIO4'

  input1: !include
    file: 'packages/input.yaml'
    vars:
      id: 1
      pin: 'GPIO5'
  input2: !include
    file: 'packages/input.yaml'
    vars:
      id: 2
      pin: 'GPIO18'

  output1: !include
    file: 'packages/output.yaml'
    vars:
      id: 1
      pin: 'GPIO12'
  output2: !include
    file: 'packages/output.yaml'
    vars:
      id: 2
      pin: 'GPIO13'
