---
substitutions:
  device_name: 'attic_shelly'
  output1_name: 'Attic'

packages:
  common: !include 'packages/common.yaml'
  device: !include 'devices/shelly/1.yaml'

output:
  - platform: 'gpio'
    pin: '${output1_gpio}'
    id: 'relay1'

light:
  - platform: 'binary'
    name: '${output1_name}'
    output: 'relay1'
    id: 'output1'
    restore_mode: 'ALWAYS_ON'
    internal: true
