---
substitutions:
  device_name: 'attic_shelly'
  output1_name: 'Attic'

packages:
  common: !include 'packages/common.yaml'
  device: !include 'packages/shelly1.yaml'

binary_sensor:
  - platform: 'gpio'
    pin: '${input1_gpio}'
    id: 'input1'
    on_state:
      then:
        homeassistant.service:
          service: 'light.toggle'
          data:
            entity_id: 'light.attic_main'

output:
  - platform: 'gpio'
    pin: '${output1_gpio}'
    id: 'relay1'

light:
  - platform: 'binary'
    name: '${output1_name}'
    output: 'relay1'
    id: 'output1'
    restore_mode: 'ALWAYS_ON'
    internal: true
