---
substitutions:
  device_area: 'Basement'
  device_id: 'basement_shelly'
  device_name: 'Basement Shelly'

packages:
  device: !include 'devices/shelly/1PM.yaml'

switch:
  - id: !extend 'switch1'
    restore_mode: 'RESTORE_DEFAULT_OFF'
