---
substitutions:
  device_name: 'basement_shelly'
  output1_name: 'Basement'

packages:
  common: !include 'packages/common.yaml'
  device: !include 'devices/shelly/1.yaml'

light:
  - platform: 'binary'
    name: '${output1_name}'
    output: 'output1'
