---
substitutions:
  device_area: 'Bathroom'
  device_id: 'bathroom_shelly_1'
  device_name: 'Bathroom Shelly 1'

packages:
  device: !include 'devices/shelly/25.yaml'

switch:
  - id: !extend 'switch2'
    restore_mode: 'RESTORE_DEFAULT_OFF'
