---
substitutions:
  device_name: 'bathroom_shelly_1'
  output1_name: 'Bathroom'
  output2_name: 'Bathroom'

packages:
  common: !include 'packages/common.yaml'
  device: !include 'packages/shelly25.yaml'

binary_sensor:
  - platform: 'gpio'
    pin: '${input1_gpio}'
    id: 'input1'
    on_click:
      - min_length: '50ms'
        max_length: '350ms'
        then:
          homeassistant.service:
            service: 'light.toggle'
            data:
              entity_id: 'light.bathroom'
      - min_length: '500ms'
        max_length: '1000ms'
        then:
          homeassistant.service:
            service: 'light.toggle'
            data:
              entity_id: 'light.bathroom_mirror'
    internal: true
  - platform: 'gpio'
    pin: '${input2_gpio}'
    id: 'input2'
    on_click:
      then:
        fan.toggle: 'output2'
    internal: true

output:
  - platform: 'gpio'
    pin: '${output1_gpio}'
    id: 'relay1'
  - platform: 'gpio'
    pin: '${output2_gpio}'
    id: 'relay2'

light:
  - platform: 'binary'
    name: '${output1_name}'
    output: 'relay1'
    id: 'output1'
    restore_mode: 'ALWAYS_ON'
    internal: true

fan:
  - platform: 'binary'
    name: '${output2_name}'
    output: 'relay2'
    id: 'output2'
