---
substitutions:
  device_name: 'bathroom_shelly_2'
  output1_name: 'Bathroom Heat'
  output2_name: 'Bathroom Mirror'

packages:
  common: !include 'packages/common.yaml'
  device: !include 'packages/shelly25.yaml'

binary_sensor:
  - platform: 'gpio'
    pin: '${input1_gpio}'
    id: 'input1'
    on_press:
      then:
        light.toggle: 'output1'
    internal: true

output:
  - platform: 'gpio'
    pin: '${output1_gpio}'
    id: 'relay1'
  - platform: 'gpio'
    pin: '${output2_gpio}'
    id: 'relay2'

light:
  - platform: 'binary'
    name: '${output1_name}'
    output: 'relay1'
    id: 'output1'

  - platform: 'binary'
    name: '${output2_name}'
    output: 'relay2'
    id: 'output2'
    restore_mode: 'ALWAYS_OFF'
    internal: true
