---
substitutions:
  device_id: 'bathroom_shelly_2'
  device_name: 'Bathroom Shelly 2'

packages:
  device: !include 'devices/shelly/25.yaml'

switch:
  - id: !extend 'switch1'
    restore_mode: 'RESTORE_DEFAULT_OFF'
