---
substitutions:
  device_name: 'bedroom_1_shelly'
  output1_name: 'Bedroom 1'

packages:
  common: !include 'packages/common.yaml'
  device: !include 'devices/shelly/1L.yaml'

light:
  - platform: 'binary'
    name: '${output1_name}'
    output: 'relay1'
    id: 'output1'
    restore_mode: 'ALWAYS_ON'
    internal: true
