---
substitutions:
  device_name: 'hallway_west_shelly'
  output1_name: 'Hallway West'
  output2_name: 'Outside'

packages:
  common: !include 'packages/common.yaml'
  device: !include 'devices/shelly/25.yaml'

light:
  - platform: 'binary'
    name: '${output1_name}'
    output: 'relay1'
    id: 'output1'
    restore_mode: 'ALWAYS_ON'
    internal: true
  - platform: 'binary'
    name: '${output2_name}'
    output: 'relay2'
    id: 'output2'
    restore_mode: 'ALWAYS_ON'
    internal: true
