---
substitutions:
  device_name: 'hallway_west_shelly'

packages:
  common: !include 'packages/common.yaml'
  device: !include 'devices/shelly/25.yaml'

light:
  - platform: 'binary'
    output: 'relay1'
    id: 'output1'
    restore_mode: 'ALWAYS_ON'
    internal: true
  - platform: 'binary'
    output: 'relay2'
    id: 'output2'
    restore_mode: 'ALWAYS_ON'
    internal: true
