---
substitutions:
  device_name: 'kitchen_shelly'
  input1_name: 'Kitchen Button'
  output1_name: 'Kitchen'

packages:
  common: !include 'packages/common.yaml'
  device: !include 'packages/shelly1.yaml'

# Inputs
binary_sensor:
  - platform: 'gpio'
    pin: '${input1_gpio}'
    name: '${input1_name}'
    on_state:
      then:
        - light.toggle: 'output_1'
    internal: true

# Outputs
output:
  - platform: 'gpio'
    pin: '${output1_gpio}'
    id: 'relay_1'

light:
  - platform: 'binary'
    name: '${output1_name}'
    output: 'relay_1'
    id: 'output_1'
