---
substitutions:
  device_name: 'kitchen_shelly'

packages:
  common: !include 'packages/common.yaml'
  device: !include 'devices/shelly/1.yaml'

switch:
  - platform: 'output'
    output: 'output1'
    name: '${device_name} Output1'
    restore_mode: 'ALWAYS_ON'
    internal: true
