---
substitutions:
  device_name: 'kitchen_shelly'
  output1_name: 'Kitchen'
  output1_type: 'light'

packages:
  common: !include 'packages/common.yaml'
  device: !include 'packages/shelly1.yaml'

binary_sensor:
  - platform: 'gpio'
    pin: '${input1_gpio}'
    id: 'input1'
    on_state:
      then:
        '${output1_type}.toggle': 'output1'
    internal: true

output:
  - platform: 'gpio'
    pin: '${output1_gpio}'
    id: 'relay1'

'${output1_type}':
  - platform: 'binary'
    name: '${output1_name}'
    output: 'relay1'
    id: 'output1'
