---
substitutions:
  device_name: 'office_desk'
  name: 'office_desk'

packages:
  tj_horner.upsy_desky: 'github://tjhorner/upsy-desky/firmware/config.yaml'
  wifi: !include 'packages/wifi.yaml'
esphome:
  name: '${device_name}'
  name_add_mac_suffix: false
