---
substitutions:
  device_area: 'Office'
  device_id: 'office_desk'
  device_name: 'Office Desk'

packages:
  device: !include
    file: 'devices/upsy_desky.yaml'
    vars:
      min_height: 70.0
      max_height: 125.0
      variant: 'omnidesk'
