---
substitutions:
  device_id: 'office_desk'
  device_name: 'Office Desk'

packages:
  common: !include 'packages/common.yaml'
  device: !include
    file: 'devices/upsy_desky.yaml'
    vars:
      variant: 'omnidesk'
