---
substitutions:
  device_board: 'esp32dev'
  device_platform: 'esp32'
  device_name: 'office_desk'

  # Defaults
  standing_desk_uart_rx_pin: '17'
  standing_desk_up_pin: '21'
  standing_desk_down_pin: '22'
  standing_desk_variant: 'uplift'
  standing_desk_min_height: '25.2'
  standing_desk_max_height: '50.8'

  # Presets
  button_bit1_pin: '21'
  button_bit2_pin: '22'
  button_bit4_pin: '19'
  button_m_pin: '18'

esphome:
  on_boot:
    then:
      # Wakes up the desk and reports height
      - uart.write:
          id: 'handset_tx'
          data:
            - 0x0

uart:
  id: 'handset_tx'
  tx_pin: 16
  baud_rate: 9600

packages:
  common: !include 'packages/common.yaml'
  standing_desk: 'github://tjhorner/esphome-standing-desk/configs/template.yaml@master'
  presets_addon: 'github://tjhorner/esphome-standing-desk/configs/addons/presets.yaml@master'
  wifi: !include 'packages/wifi.yaml'

select:
  - platform: 'template'
    name: '${device_name} Height Decoder Variant'
    entity_category: 'config'
    optimistic: true
    restore_value: true
    options:
      - 'uplift'
      - 'jarvis'
    initial_option: '${standing_desk_variant}'
    on_value:
      then:
        lambda: 'id(desk_height)->set_decoder_variant(x);'
  - platform: 'template'
    name: '${device_name} Height Units'
    entity_category: 'config'
    optimistic: true
    restore_value: true
    options:
      - 'in'
      - 'cm'
    initial_option: 'in'
    on_value:
      then:
        lambda: |
          id(desk_height)->set_unit_of_measurement(x);
          id(target_desk_height)->traits.set_unit_of_measurement(x);
number:
  - platform: 'template'
    name: '${device_name} Min Target Height'
    entity_category: 'config'
    min_value: 0
    max_value: 150
    step: 0.1
    optimistic: true
    restore_value: true
    initial_value: '${standing_desk_min_height}'
    on_value:
      then:
        lambda: |
          id(target_desk_height)->traits.set_min_value(x);
  - platform: 'template'
    name: '${device_name} Max Target Height'
    entity_category: 'config'
    min_value: 0
    max_value: 150
    step: 0.1
    optimistic: true
    restore_value: true
    initial_value: '${standing_desk_max_height}'
    on_value:
      then:
        lambda: |
          id(target_desk_height)->traits.set_max_value(x);

status_led:
  pin: 'GPIO23'