---
substitutions:
  device_board: 'esp32dev'
  device_platform: 'esp32'
  device_name: 'office_desk'

  # Defaults
  standing_desk_uart_rx_pin: '17'
  standing_desk_up_pin: '21'
  standing_desk_down_pin: '22'
  standing_desk_variant: 'uplift'
  standing_desk_min_height: '25.2'
  standing_desk_max_height: '50.8'

  # Presets
  button_bit1_pin: '21'
  button_bit2_pin: '22'
  button_bit4_pin: '19'
  button_m_pin: '18'

packages:
  common: !include 'packages/common.yaml'
  wifi: !include 'packages/wifi.yaml'
  standing_desk: 'github://tjhorner/esphome-standing-desk/configs/template.yaml@master'
  presets_addon: 'github://tjhorner/esphome-standing-desk/configs/addons/presets.yaml@master'

esphome:
  on_boot:
    then:
      # Wakes up the desk and reports height.
      uart.write:
        id: 'handset'
        data:
          - 0x00

uart:
  baud_rate: 9600
  tx_pin: 'GPIO16'
  id: 'handset'

status_led:
  pin: 'GPIO23'