---
substitutions:
  friendly_name: 'Office Voice Assistant'
  name: 'office_voice_assistant'

packages:
  Nabu Casa.Home Assistant Voice PE: 'github://esphome/voice-kit/home-assistant-voice.yaml@0579e7b9d8504264719c593474c85447253c9dc1'

esphome:
  name: '${name}'
  name_add_mac_suffix: false
  friendly_name: '${friendly_name}'

api:
  encryption:
    key: !secret 'api.encryption.key'

wifi:
  networks:
    - ssid: !secret 'wifi.ssid'
      password: !secret 'wifi.password'
      hidden: true
