---
substitutions:
  device_id: 'toilet_shelly'
  device_name: 'Toilet Shelly'

packages:
  device: !include 'devices/shelly/25.yaml'

switch:
  - id: !extend 'switch2'
    restore_mode: 'RESTORE_DEFAULT_OFF'
