---
substitutions:
  device_name: 'toilet_shelly'
  input1_name: 'Toilet Upper Button'
  input2_name: 'Toilet Lower Button'
  output1_name: 'Toilet Light'
  output2_name: 'Toilet Fan'

<<: !include 'common/common.yaml'
<<: !include 'common/shelly25.yaml'

# Inputs
binary_sensor:
  - platform: 'gpio'
    pin: 'GPIO13'
    name: '${input1_name}'
  - platform: 'gpio'
    pin: 'GPIO5'
    name: '${input2_name}'
    on_press:
      then:
        - fan.toggle: 'output_2'
  - platform: 'gpio'
    pin: 'GPIO16'
    name: 'ADE7953 IRQ'
    internal: true

# Outputs
output:
  - platform: 'gpio'
    pin: 'GPIO15'
    id: 'relay_1'
  - platform: 'gpio'
    pin: 'GPIO4'
    id: 'relay_2'

light:
  - platform: 'binary'
    output: 'relay_2'
    name: '${output1_name}'
    id: 'output_1'
    restore_mode: 'ALWAYS_ON'
    internal: true

fan:
  - platform: 'binary'
    output: 'relay_1'
    name: '${output2_name}'
    id: 'output_2'
