---
substitutions:
  device_name: 'toilet_shelly'
  output1_name: 'Toilet'
  output2_name: 'Toilet'

packages:
  common: !include 'packages/common.yaml'
  device: !include 'packages/shelly25.yaml'

# Inputs
binary_sensor:
  - platform: 'gpio'
    pin: '${input1_gpio}'
    id: 'input1'
    internal: true
  - platform: 'gpio'
    pin: '${input2_gpio}'
    id: 'input2'
    on_press:
      then:
        fan.toggle: 'output2'
    internal: true

# TODO: Move this to `packages/shelly25.yaml`.
output:
  - platform: 'gpio'
    pin: '${output1_gpio}'
    id: 'relay1'
  - platform: 'gpio'
    pin: '${output2_gpio}'
    id: 'relay2'

# Output 1 is connected to `light.toilet` so that it can be power cycled if
# necessary (without turning off mains power). Since this should be almost
# never need to be done, output 1 should be permanently on.
light:
  - platform: 'binary'
    name: '${output1_name}'
    output: 'relay1'
    id: 'output1'
    restore_mode: 'ALWAYS_ON'
    internal: true

fan:
  - platform: 'binary'
    name: '${output2_name}'
    output: 'relay2'
    id: 'output2'
