---
substitutions:
  device_name: 'toilet_shelly'
  output2_name: 'Toilet'

packages:
  common: !include 'packages/common.yaml'
  device: !include 'devices/shelly/25.yaml'

switch:
  - platform: 'output'
    output: 'output1'
    name: '${device_name} Output1'
    restore_mode: 'ALWAYS_ON'
    internal: true

fan:
  - platform: 'binary'
    name: '${output2_name}'
    output: 'output2'
