---
substitutions:
  device_name: 'toilet_shelly'
  output2_name: 'Toilet'

packages:
  common: !include 'packages/common.yaml'
  device: !include 'devices/shelly/25.yaml'

light:
  - platform: 'binary'
    output: 'relay1'
    id: 'output1'
    restore_mode: 'ALWAYS_ON'
    internal: true

fan:
  - platform: 'binary'
    name: '${output2_name}'
    output: 'relay2'
    id: 'output2'
