---
substitutions:
  device_id: 'toilet_shelly'
  device_name: 'Toilet Shelly'
  output2_component: 'fan'
  output2_platform: 'binary'
  output2_name: 'Toilet'
  output2_restore_mode: 'RESTORE_DEFAULT_OFF'
  output2_internal: 'false'

packages:
  common: !include 'packages/common.yaml'
  device: !include 'devices/shelly/25.yaml'
