---
substitutions:
  device_name: 'toilet_shelly'
  input1_name: 'Toilet Upper Button'
  input2_name: 'Toilet Lower Button'
  output1_name: 'Toilet Light'
  output2_name: 'Toilet Fan'
  <<: !include 'common/substitutions/shelly25.yaml'

<<: !include 'common/common.yaml'
<<: !include 'common/shelly25.yaml'

# Inputs
binary_sensor:
  - platform: 'gpio'
    pin: '${input1_gpio}'
    name: '${input1_name}'
  - platform: 'gpio'
    pin: '${input2_gpio}'
    name: '${input2_name}'
    on_press:
      then:
        - fan.toggle: 'output_2'
  - !include 'common/binary_sensor/shelly25.yaml'

# Outputs
output:
  - platform: 'gpio'
    pin: '${output1_gpio}'
    id: 'relay_1'
  - platform: 'gpio'
    pin: '${output2_gpio}'
    id: 'relay_2'

# Output 1 is connected to `light.toilet` so that it can be power cycled if
# necessary (without turning off mains power). Since this should be almost
# never need to be done, output 1 should be permanently on.
light:
  - platform: 'binary'
    name: '${output1_name}'
    output: 'relay_1'
    id: 'output_1'
    restore_mode: 'ALWAYS_ON'
    internal: true

fan:
  - platform: 'binary'
    name: '${output2_name}'
    output: 'relay_2'
    id: 'output_2'
