---
substitutions:
  name: 'upsy-desky-580310'
packages:
  tj_horner.upsy_desky: 'github://tjhorner/upsy-desky/firmware/config.yaml'
esphome:
  name: '${name}'
  name_add_mac_suffix: false

wifi:
  ssid: !secret 'wifi.ssid'
  password: !secret 'wifi.password'
