---
substitutions:
  device_id: 'zigbee_gateway_backup'
  device_name: 'Zigbee Gateway Backup'

packages:
  common: !include 'packages/common.yaml'
  device: !include 'devices/tubeszb/cc2652_poe.yaml'
