---
substitutions:
  device_board: 'esp-wrover-kit'
  device_platform: 'esp32'
  device_name: 'zigbee_gateway'

packages:
  common: !include 'packages/common.yaml'

ethernet:
  type: 'LAN8720'
  mdc_pin: 'GPIO23'
  mdio_pin: 'GPIO18'
  clk_mode: 'GPIO17_OUT'
  power_pin: 'GPIO12'

# TODO: Remove this.
web_server:
  port: 80

script:
  - id: 'firmware_update_mode'
    then:
      - switch.turn_on: 'zBSL'
      - delay: '1s'
      - switch.turn_on: 'zRST_gpio'
      - delay: '1s'
      - switch.turn_off: 'zRST_gpio'
      - delay: '11s'
      - switch.turn_off: 'zBSL'
      - logger.log: 'Please try update with cc-bsl tool now'
      - logger.log: 'cc-bsl usage: cc-bsl.py -p socket://ip-of-gw:6638 -evw firmware.hex'

switch:
  - platform: 'gpio'
    pin: 33
    id: 'zRST_gpio'
    restore_mode: 'ALWAYS_OFF'
    inverted: true
  - platform: 'template'
    id: 'zRST'
    turn_on_action:
      - switch.turn_on: 'zRST_gpio'
      - delay: '15ms'
      - switch.turn_off: 'zRST_gpio'

  - platform: 'gpio'
    pin: 32
    id: 'zBSL'
    restore_mode: 'ALWAYS_OFF'
    inverted: true

  - platform: 'template'
    name: '${device_name} Firmware Update Mode'
    turn_on_action:
      script.execute: 'firmware_update_mode'
    turn_off_action:
      switch.toggle: 'zRST'

uart:
  id: 'uart_bus'
  rx_pin: 'GPIO5'
  tx_pin: 'GPIO16'
  baud_rate: 115200

external_components:
  # TODO: Point back to `oxan/esphome-stream-server` after oxan/esphome-stream-server#15 is merged.
  - source: 'github://joshuaspence/esphome-stream-server@sensor'

stream_server:
  uart_id: 'uart_bus'
  id: 'main'

binary_sensor:
  - platform: 'stream_server'
    stream_server: 'main'
    name: '${device_name} Connected'
