---
env:
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'airbnb-base'
  - 'plugin:eslint-comments/recommended'
parserOptions:
  ecmaVersion: 'latest'
  sourceType: 'module'
rules:
  eslint-comments/disable-enable-pair:
    - 'error'
    - allowWholeFile: true
  max-len: 'off'
  no-unused-vars:
    - 'error'
    - args: 'none'

  # This doesn't work without outside of a Node project (see import-js/eslint-plugin-import#2096).
  import/no-unresolved: 'off'
