---
env:
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - 'airbnb-base'
rules:
  max-len: 'off'

  # This doesn't work without outside of a Node project (see import-js/eslint-plugin-import#2096).
  import/no-unresolved: 'off'
