---
external_converters: []
devices: 'devices.yaml'
groups: 'groups.yaml'
homeassistant: true
mqtt:
  base_topic: 'zigbee2mqtt'
serial:
  port: 'tcp://zigbee_gateway.spence.network:6638'
advanced:
  pan_id: 43081
  channel: 25
  network_key: '!secret network_key'
  log_directory: '/config/zigbee2mqtt'
  log_file: 'zigbee2mqtt.log'
  log_output:
    - 'file'
  homeassistant_legacy_entity_attributes: false
  homeassistant_legacy_triggers: false
  legacy_api: false
  last_seen: 'ISO_8601'
device_options: {}
availability:
  active:
    timeout: 10
  passive:
    timeout: 180
