---
homeassistant:
  legacy_triggers: false
  legacy_entity_attributes: false
availability:
  active:
    timeout: 10
  passive:
    timeout: 180
external_converters:
  - '/config/zigbee2mqtt/converters'
serial:
  port: 'tcp://zigbee_gateway.local:6638'
devices: 'devices.yaml'
groups: 'groups.yaml'
device_options:
  homeassistant:
    action_source_name: null
    action_user: null
    inside_status_led:
      entity_category: 'config'
      icon: 'mdi:led-on'
    language:
      entity_category: 'config'
      icon: 'mdi:translate'
    one_touch_locking:
      entity_category: 'config'
      icon: 'mdi:gesture-tap'
    privacy_mode_button:
      entity_category: 'config'
    wrong_code_entry_limit:
      entity_category: 'config'
advanced:
  legacy_api: false
  legacy_availability_payload: false
  log_output:
    - 'file'
  log_directory: '/config/zigbee2mqtt'
  log_file: 'zigbee2mqtt.log'
  pan_id: 43081
  channel: 25
  last_seen: 'ISO_8601'
  network_key: '!secret network_key'
