---
homeassistant:
  legacy_triggers: false
  legacy_entity_attributes: false
availability:
  active:
    timeout: 10
  passive:
    timeout: 180
external_converters: []
serial:
  port: 'tcp://zigbee_gateway.spence.network:6638'
frontend:
  port: 8099
devices: 'devices.yaml'
groups: 'groups.yaml'
device_options: {}
advanced:
  legacy_api: false
  log_output:
    - 'file'
  log_directory: '/config/zigbee2mqtt'
  log_file: 'zigbee2mqtt.log'
  pan_id: 43081
  channel: 25
  last_seen: 'ISO_8601'
  network_key: '!secret network_key'
