---
homeassistant:
  legacy_triggers: false
  legacy_entity_attributes: false
availability:
  active:
    timeout: 10
  passive:
    timeout: 180
external_converters:
  - '/config/zigbee2mqtt/converters/yale'
serial:
  port: 'tcp://zigbee_gateway.local:6638'
devices: 'devices.yaml'
groups: 'groups.yaml'
device_options:
  homeassistant:
    action_source_name:
      enabled_by_default: false
    action_source_user:
      enabled_by_default: false
    device_temperature:
      enabled_by_default: false
    power_outage_count:
      entity_category: 'diagnostic'
      enabled_by_default: false
advanced:
  legacy_api: false
  legacy_availability_payload: false
  log_rotation: false
  log_output:
    - 'file'
  log_directory: '/config/zigbee2mqtt'
  log_file: 'zigbee2mqtt.log'
  pan_id: 43081
  channel: 25
  last_seen: 'ISO_8601'
  network_key: '!secret network_key'
