---
title: 'Network'
icon: 'mdi:security'
path: 'security'
cards:
  - type: 'entities'
    title: 'UniFi'
    icon: 'mdi:router-network'
    entities:
      - type: 'section'
        label: 'NVR'
      - entity: 'binary_sensor.unvr_hdd_1'
        name: 'HDD 1'
      - entity: 'binary_sensor.unvr_hdd_2'
        name: 'HDD 2'
      - entity: 'sensor.unvr_recording_capacity'
        name: 'Recording Capacity'
      - entity: 'sensor.unvr_storage_utilization'
        name: 'Storage Utilization'
      - entity: 'sensor.unvr_uptime'
        name: 'Uptime'
      - entity: 'sensor.unvr_cpu_temperature'
        name: 'CPU Temperature'
      - entity: 'sensor.unvr_cpu_utilization'
        name: 'CPU Utilization'
      - entity: 'sensor.unvr_memory_utilization'
        name: 'Memory Utilization'
