---
alarm_control_panel:
  - platform: 'manual'
    name: 'Alarm'
    code: !secret 'alarm.code'

automation:
  - id: 'c9e5b5d8-3d97-404c-8158-50956278fb72'
    alias: 'Alarm Notify'
    trigger:
      platform: 'state'
      entity_id: 'alarm_control_panel.alarm'
      to: 'triggered'

    # TODO: Add siren (see https://github.com/stanvx/Home-Assistant-Configuration/blob/master/packages/alarm_system.yaml#L52).
    action:
      - service: 'notify.notify'
        data:
          message: 'The alarm has been triggered!'
      - service: 'light.turn_on'
        entity_id: 'all'

    trace:
      stored_traces: 20

  - id: '5350a641-9769-4587-b0a0-3dd2ba6d0fd3'
    alias: 'Alarm Trigger'
    trigger:
      platform: 'state'
      entity_id:
        - 'binary_sensor.back_door'
        - 'binary_sensor.dining_room_sliding_door'
        - 'binary_sensor.front_door'
        - 'binary_sensor.living_room_sliding_door'
      to: 'on'
    condition:
      condition: 'state'
      entity_id: 'alarm_control_panel.alarm'
      state: 'armed_away'
    action:
      service: 'alarm_control_panel.alarm_trigger'
      entity_id: 'alarm_control_panel.alarm'
    trace:
      stored_traces: 20
