---
binary_sensor:
  # Rooms
  - platform: 'group'
    name: 'Hallway Occupancy'
    unique_id: 'b51864e4-8ad0-435a-9b6a-d6b4656cc643'
    device_class: 'motion'
    entities:
      - 'binary_sensor.hallway_east_occupancy'
      - 'binary_sensor.hallway_west_occupancy'

  - platform: 'group'
    name: 'Kitchen Occupancy'
    unique_id: '87788c48-7ac1-49e1-949c-14aa1d6f7a41'
    device_class: 'motion'
    entities:
      - 'binary_sensor.kitchen_north_occupancy'
      - 'binary_sensor.kitchen_south_occupancy'

  - platform: 'group'
    name: 'Living Room Occupancy'
    unique_id: 'd3b33bf0-abab-429b-94eb-21120ec6a7cf'
    device_class: 'motion'
    entities:
      - 'binary_sensor.living_room_north_occupancy'
      - 'binary_sensor.living_room_south_occupancy'

  # Doors
  - platform: 'group'
    name: 'External Doors'
    unique_id: 'e2a45096-93a4-4cb8-ba63-37fc83082b1d'
    device_class: 'door'
    entities:
      - 'binary_sensor.back_door'
      - 'binary_sensor.dining_room_sliding_door'
      - 'binary_sensor.front_door'
      - 'binary_sensor.living_room_sliding_door'
  - platform: 'group'
    name: 'Internal Doors'
    unique_id: 'b554e98a-3b64-4a15-99b3-ea7bb72e0290'
    device_class: 'door'
    entities:
      - 'binary_sensor.attic_door'
      - 'binary_sensor.basement_door'
      - 'binary_sensor.bathroom_door'
      - 'binary_sensor.bedroom_1_door'
      - 'binary_sensor.bedroom_2_door'
      - 'binary_sensor.kitchen_door'
      - 'binary_sensor.laundry_door'
      - 'binary_sensor.linen_closet_door'
      - 'binary_sensor.office_door'
      - 'binary_sensor.pantry_door'
      - 'binary_sensor.toilet_door'

  # Windows
  - platform: 'group'
    name: 'All Windows'
    unique_id: '6df77c0b-2557-4c0a-b9cc-708f14a57cde'
    device_class: 'window'
    entities:
      - 'binary_sensor.bedroom_1_east_window'
      - 'binary_sensor.bedroom_1_south_window'
      - 'binary_sensor.bedroom_2_window'
      - 'binary_sensor.kitchen_window'
      - 'binary_sensor.laundry_window'
      - 'binary_sensor.office_window'

  # Occupancy
  - platform: 'group'
    name: 'External Occupancy'
    unique_id: '268afc86-a304-4580-9736-672335b6e709'
    device_class: 'motion'
    entities:
      - 'binary_sensor.back_yard_occupancy'
      - 'binary_sensor.clothes_line_occupancy'
      - 'binary_sensor.front_yard_occupancy'
      - 'binary_sensor.side_yard_occupancy'
  - platform: 'group'
    name: 'Internal Occupancy'
    unique_id: 'b205d8cb-5dc4-41fb-9720-7a47a0ea63d3'
    device_class: 'motion'
    entities:
      - 'binary_sensor.bathroom_occupancy'
      - 'binary_sensor.bedroom_1_occupancy'
      - 'binary_sensor.bedroom_2_occupancy'
      - 'binary_sensor.dining_room_occupancy'
      - 'binary_sensor.hallway_occupancy'
      - 'binary_sensor.kitchen_occupancy'
      - 'binary_sensor.laundry_occupancy'
      - 'binary_sensor.living_room_occupancy'
      - 'binary_sensor.office_occupancy'
      - 'binary_sensor.toilet_occupancy'
