---
cast: {}
homeassistant:
  customize_glob:
    media_player.*_display: {}
    media_player.*_speaker:
      device_class: 'speaker'
      icon: 'mdi:speaker'
    media_player.*_tv:
      device_class: 'tv'
      icon: 'mdi:television'
