---
automation:
  - id: 'e672aca4-7227-422f-b4e5-af477cb67cbf'
    alias: 'Device Registry Notification'
    trigger:
      platform: 'event'
      event_type: 'device_registry_updated'
      event_data:
        action: 'create'
    variables:
      device_id: '{{ trigger.event.data.device_id }}'
    action:
      service: 'persistent_notification.create'
      data:
        title: 'New device registered'
        message: |-
          [{{ device_attr(device_id, 'name_by_user') | default(device_attr(device_id, 'name'), true) }}](/config/devices/device/{{device_id}}) was added to the device registry.
        notification_id: 'device_registry_{{ device_id }}'
    mode: 'parallel'
