---
automation:
  - id: '18a4357c-a3bb-4336-a184-43dea3d82c86'
    alias: 'Doorbell Notification'
    trigger:
      platform: 'state'
      entity_id: 'binary_sensor.doorbell_occupancy'
      from: 'off'
      to: 'on'
    action:
      - service: 'media_player.volume_set'
        data:
          volume_level: 0.7
        target:
          entity_id: &media_player 'media_player.all'
      - repeat:
          sequence:
            - service: 'media_player.play_media'
              data:
                media_content_id: 'media-source://media_source/local/unifi_protect_chime.wav'
                media_content_type: 'music'
                announce: true
              target:
                entity_id: *media_player
            - wait_for_trigger: &media_player_idle_wait
                platform: 'state'
                entity_id: *media_player
                to: 'idle'

            - service: 'tts.cloud_say'
              data:
                entity_id: *media_player
                message: 'Someone is at the door'
                cache: true
            - *media_player_idle_wait

            - delay: 5
          until:
            or:
              - condition: 'state'
                entity_id: 'binary_sensor.front_door'
                state: 'on'
              - condition: 'template'
                value_template: '{{ repeat.index > 2 }}'
    mode: 'single'
