---
template:
  - trigger:
      - platform: 'homeassistant'
        event: 'start'
      - platform: 'time_pattern'
        hours: '*'
      - platform: 'state'
        entity_id: 'binary_sensor.zigbee2mqtt_state'
    sensor:
      - name: 'Firmware Updates Available'
        unique_id: '51576e42-ce49-429a-8351-2142de129a26'
        state: >-
          {% set ns = namespace(sensors = []) %}
          {% for sensor in states.binary_sensor %}
          {%   if "_update_available" in sensor.entity_id and "e7f4758baacf9f1e04c2a6664d6aa37a" in device_attr(sensor.entity_id, "config_entries") and sensor.state == "on" %}
          {%     set ns.sensors = ns.sensors + [sensor.entity_id] %}
          {%   endif %}
          {% endfor %}

          {{ ns.sensors | count }}
        availability: '{{ states("binary_sensor.zigbee2mqtt_state") == "on" }}'

automation:
  - alias: 'Firmware Updates Available'
    id: '9fa74084-47b9-492c-9731-e4b09ea61556'
    trigger:
      platform: 'state'
      entity_id: 'sensor.firmware_updates_available'
    action:
      if:
        condition: 'numeric_state'
        entity_id: 'sensor.firmware_updates_available'
        above: 0
      then:
        service: 'persistent_notification.create'
        data:
          message: 'There are {{ states.sensor.firmware_updates_available.state }} firmware updates available.'
          title: 'Firmware Update Available'
          notification_id: 'firmware-updates-available'
      else:
        service: 'persistent_notification.dismiss'
        data:
          notification_id: 'firmware-updates-available'
    mode: 'restart'
