---
hacs:
  token: !secret 'hacs.github_token'

homeassistant:
  customize:
    sensor.hacs:
      friendly_name: 'HACS'

# Load themes installed with HACS.
frontend:
  themes: !include_dir_merge_named '../themes'
