---
# TODO: Add automation to check that add-ons are running.
automation:
  - id: 'b00c4a0f-8d93-4082-a82d-fd62b042e840'
    alias: 'Home Assistant Update Available'
    trigger:
      platform: 'state'
      entity_id: 'update.home_assistant_core'
    action:
      - choose:
          - conditions: '{{ trigger.to_state.state == "on" }}'
            sequence:
              service: 'persistent_notification.create'
              data:
                title: 'Update Available'
                message: >-
                  [Home Assistant {{ state_attr('update.home_assistant_core', 'latest_version') }}](/hassio/update-available/core) is available.
                notification_id: 'update_available_homeassistant'
          - conditions: '{{ trigger.to_state.state == "off" }}'
            sequence:
              service: 'persistent_notification.dismiss'
              data:
                notification_id: 'update_available_homeassistant'
  - id: 'aa2c8c93-8c99-48e4-9070-a80c07f8c7cf'
    alias: 'HassOS Update Available'
    trigger:
      platform: 'state'
      entity_id: 'update.hassos'
    action:
      - choose:
          - conditions: '{{ trigger.to_state.state == "on" }}'
            sequence:
              service: 'persistent_notification.create'
              data:
                title: 'Update Available'
                message: >-
                  [HassOS {{ state_attr('update.hassos', 'latest_version') }}](/hassio/update-available/os) is available.
                notification_id: 'update_available_hassos'
          - conditions: '{{ trigger.to_state.state == "off" }}'
            sequence:
              service: 'persistent_notification.dismiss'
              data:
                notification_id: 'update_available_hassos'

  - id: 'ec311ea9-3c96-4505-9bf3-b393d9e7e1f2'
    alias: 'ESPHome Add-on Update Notification'
    use_blueprint:
      path: 'addon_update_notification.yaml'
      input:
        addon: '5c53de3b_esphome'
        sensor: 'update.esphome'
  - id: '1d219271-b31c-455b-b37e-1064c935d2fe'
    alias: 'Google Drive Backup Add-on Update Notification'
    use_blueprint:
      path: 'addon_update_notification.yaml'
      input:
        addon: 'cebe7a76_hassio_google_drive_backup'
        sensor: 'update.google_drive_backup'
  - id: '96e43b0a-bc91-42ba-9eb1-f63ec14e976d'
    alias: 'Mosquitto Add-on Update Notification'
    use_blueprint:
      path: 'addon_update_notification.yaml'
      input:
        addon: 'core_mosquitto'
        sensor: 'update.mosquitto'
  - id: 'cdfd7283-2c2a-4afd-a7e5-a5c08a6ba193'
    alias: 'Terminal SSH Add-on Update Notification'
    use_blueprint:
      path: 'addon_update_notification.yaml'
      input:
        addon: 'core_ssh'
        sensor: 'update.terminal_ssh'
  - id: '7a6bc69a-2632-40d3-848c-fe8d6006b840'
    alias: 'Zigbee2MQTT Add-on Update Notification'
    use_blueprint:
      path: 'addon_update_notification.yaml'
      input:
        addon: '45df7312_zigbee2mqtt'
        sensor: 'update.zigbee2mqtt'

