---
sensor:
  - platform: 'command_line'
    command: 'curl --header "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" http://supervisor/info | jq .data'
    name: 'Current Version'
    unique_id: 'b6711ddd-1820-4eef-8efc-82d76c8177b0'
    value_template: '{{ value_json.homeassistant }}'
    scan_interval: 600
    json_attributes:
      - 'hassos'

automation:
  - id: 'b00c4a0f-8d93-4082-a82d-fd62b042e840'
    alias: 'Home Assistant Update Available'
    trigger:
      platform: 'state'
      entity_id:
        - 'sensor.current_version'
        - 'sensor.latest_version'
    condition:
      condition: 'not'
      conditions:
        condition: 'or'
        conditions:
          - condition: 'state'
            entity_id: 'sensor.current_version'
            state: 'unavailable'
          - condition: 'state'
            entity_id: 'sensor.latest_version'
            state: 'unavailable'
    action:
      - choose:
          - conditions: '{{ states("sensor.current_version") != states("sensor.latest_version") }}'
            sequence:
              service: 'persistent_notification.create'
              data:
                title: 'Update Available'
                message: >-
                  [Home Assistant {{ states("sensor.latest_version") }}](/hassio/update-available/core) is available.'
                notification_id: 'update_available_homeassistant'
        default:
          service: 'persistent_notification.dismiss'
          data:
            notification_id: 'update_available_homeassistant'

      - choose:
          - conditions: '{{ state_attr("sensor.current_version", "hassos") != state_attr("sensor.latest_version", "os") }}'
            sequence:
              service: 'persistent_notification.create'
              data:
                title: 'Update Available'
                message: 'HassOS {{ state_attr("sensor.latest_version", "os") }} is available.'
                notification_id: 'update_available_hassos'
        default:
          service: 'persistent_notification.dismiss'
          data:
            notification_id: 'update_available_hassos'

  - id: 'ec311ea9-3c96-4505-9bf3-b393d9e7e1f2'
    alias: 'ESPHome Add-on Update Notification'
    use_blueprint:
      path: 'addon_update_notification.yaml'
      input:
        addon: 'a0d7b954_esphome'
        name: 'ESPHome'
        update_available_sensor: 'binary_sensor.esphome_update_available'
        current_version_sensor: 'sensor.esphome_version'
        newest_version_sensor: 'sensor.esphome_newest_version'
  - id: '1d219271-b31c-455b-b37e-1064c935d2fe'
    alias: 'Google Drive Backup Add-on Update Notification'
    use_blueprint:
      path: 'addon_update_notification.yaml'
      input:
        addon: 'cebe7a76_hassio_google_drive_backup'
        name: 'Google Drive Backup'
        update_available_sensor: 'binary_sensor.google_drive_backup_update_available'
        current_version_sensor: 'sensor.google_drive_backup_version'
        newest_version_sensor: 'sensor.google_drive_backup_newest_version'
  - id: '96e43b0a-bc91-42ba-9eb1-f63ec14e976d'
    alias: 'Mosquitto Add-on Update Notification'
    use_blueprint:
      path: 'addon_update_notification.yaml'
      input:
        addon: 'core_mosquitto'
        name: 'Mosquitto broker'
        update_available_sensor: 'binary_sensor.mosquitto_broker_update_available'
        current_version_sensor: 'sensor.mosquitto_broker_version'
        newest_version_sensor: 'sensor.mosquitto_broker_newest_version'
  - id: 'cdfd7283-2c2a-4afd-a7e5-a5c08a6ba193'
    alias: 'Terminal SSH Add-on Update Notification'
    use_blueprint:
      path: 'addon_update_notification.yaml'
      input:
        addon: 'core_ssh'
        name: 'Terminal & SSH'
        update_available_sensor: 'binary_sensor.terminal_ssh_update_available'
        current_version_sensor: 'sensor.terminal_ssh_version'
        newest_version_sensor: 'sensor.terminal_ssh_newest_version'
  - id: '7a6bc69a-2632-40d3-848c-fe8d6006b840'
    alias: 'Zigbee2MQTT Add-on Update Notification'
    use_blueprint:
      path: 'addon_update_notification.yaml'
      input:
        addon: '45df7312_zigbee2mqtt_edge'
        name: 'Zigbee2mqtt'
        update_available_sensor: 'binary_sensor.zigbee2mqtt_update_available'
        current_version_sensor: 'sensor.zigbee2mqtt_version'
        newest_version_sensor: 'sensor.zigbee2mqtt_newest_version'

# TODO: Add automation to check that add-ons are running.
