---
automation:
  - id: '6097ac1d-78f0-43e8-b466-5f7d76148227'
    alias: 'Bedroom 1 Dimmer Switch'
    use_blueprint:
      path: 'hue_dimmer_switch.yaml'
      input:
        remote: 'Bedroom 1 Dimmer Switch'
        on_press:
          scene: 'scene.bedroom_1_awake'
        up_press:
          service: 'light.turn_on'
          target:
            entity_id: 'light.bedroom_1'
          data:
            brightness_step_pct: 25
        down_press:
          service: 'light.turn_on'
          target:
            entity_id: 'light.bedroom_1'
          data:
            brightness_step_pct: -25
        off_press:
          scene: 'scene.bedroom_1_sleep'
