---
automation:
  - id: '6097ac1d-78f0-43e8-b466-5f7d76148227'
    alias: 'Bedroom 1 Dimmer Switch'
    use_blueprint:
      path: 'hue_dimmer_switch.yaml'
      input:
        remote: 'Bedroom 1 Dimmer Switch'
        on_press_release:
          action: 'light.turn_on'
          target:
            entity_id: 'light.bedroom_1'
          data:
            brightness: 255
        on_hold_release:
          scene: 'scene.bedroom_1_awake'
        up_press_release:
          action: 'light.turn_on'
          target:
            entity_id: 'light.bedroom_1'
          data:
            brightness_step_pct: 20
        down_press_release:
          action: 'light.turn_on'
          target:
            entity_id: 'light.bedroom_1'
          data:
            brightness_step_pct: -20
        off_press_release:
          action: 'light.turn_off'
          target:
            entity_id: 'light.bedroom_1'
        off_hold_release:
          scene: 'scene.bedroom_1_sleep'

  - id: 'a492e89e-2e0d-4b86-8fbf-124b5f783b71'
    alias: 'Bedroom 2 Dimmer Switch'
    use_blueprint:
      path: 'hue_dimmer_switch.yaml'
      input:
        remote: 'Bedroom 2 Dimmer Switch'
        on_press_release:
          action: 'light.turn_on'
          target:
            entity_id: 'light.bedroom_2'
          data:
            brightness: 255
        on_hold_release:
          scene: 'scene.bedroom_2_awake'
        up_press_release:
          action: 'light.turn_on'
          target:
            entity_id: 'light.bedroom_2'
          data:
            brightness_step_pct: 20
        down_press_release:
          action: 'light.turn_on'
          target:
            entity_id: 'light.bedroom_2'
          data:
            brightness_step_pct: -20
        off_press_release:
          action: 'light.turn_off'
          target:
            entity_id: 'light.bedroom_2'
        off_hold_release:
          scene: 'scene.bedroom_2_sleep'
