---
lock:
  - platform: 'group'
    unique_id: '6bc00591-4387-4e68-8cdd-15a642fc0d5f'
    name: 'All'
    entities:
      - 'lock.front_door'
      - 'lock.back_door'

automation:
  - id: 'afc8f43d-f33a-4e69-9a77-8b6f46da32e0'
    alias: 'Back Door Events'
    use_blueprint:
      path: 'yale_assure_events.yaml'
      input:
        lock: 'Back Door Lock'
        keypad_unlock:
          - variables: &variables
              users:
                - 'josh'
                - 'lily'
              friendly_name: >-
                {% if user == 1 %}
                  master code
                {% else %}
                  {{ state_attr('person.' ~ users[user - 2], 'friendly_name') }}
                {% endif %}
          - action: 'logbook.log'
            data:
              message: 'was unlocked by {{ friendly_name }}'
              <<: &back_door
                name: 'Back Door'
                entity_id: 'lock.back_door'
                domain: 'lock'
        manual_lock:
          action: 'logbook.log'
          data:
            message: 'was locked manually'
            <<: *back_door
        manual_unlock:
          action: 'logbook.log'
          data:
            message: 'was unlocked manually'
            <<: *back_door
        touch_lock:
          action: 'logbook.log'
          data:
            message: 'was locked by touchscreen'
            <<: *back_door
        pin_code_added:
          action: 'logbook.log'
          data:
            message: 'was setup with a PIN code for user {{ user }}'
            <<: *back_door
  - id: 'b8ac47a4-7b1c-4baf-b891-15b7242a0e8c'
    alias: 'Front Door Events'
    use_blueprint:
      path: 'yale_assure_events.yaml'
      input:
        lock: 'Front Door Lock'
        keypad_unlock:
          - variables: *variables
          - action: 'logbook.log'
            data:
              message: 'was unlocked by {{ friendly_name }}'
              <<: &front_door
                name: 'Front Door'
                entity_id: 'lock.front_door'
                domain: 'lock'
        manual_lock:
          action: 'logbook.log'
          data:
            message: 'was locked manually'
            <<: *front_door
        manual_unlock:
          action: 'logbook.log'
          data:
            message: 'was unlocked manually'
            <<: *front_door
        touch_lock:
          action: 'logbook.log'
          data:
            message: 'was locked by touchscreen'
            <<: *front_door
        pin_code_added:
          action: 'logbook.log'
          data:
            message: 'was setup with a PIN code for user {{ user }}'
            <<: *front_door
