---
sensor:
  - platform: 'template'
    sensors:
      low_battery:
        friendly_name: 'Low Battery'
        unique_id: '2dbdee74-5c79-4f10-ae67-e6c8aead4d61'
        unit_of_measurement: 'devices'
        value_template: >-
          {% set ns = namespace(entities=[], mobile_app_sensors=[]) %}
          {%
            set sensors = states.sensor
              | selectattr('attributes.device_class', 'eq', 'battery')
              | rejectattr('state', 'in', ['unavailable', 'unknown'])
              | list
          %}

          {% for sensor in sensors %}
            {% if 'mobile_app' in device_attr(sensor.entity_id, 'identifiers') | map(attribute=0) %}
              {% set ns.mobile_app_sensors = ns.mobile_app_sensors + [sensor.entity_id] %}
            {% endif %}
          {% endfor %}
          {% set sensors = sensors | rejectattr('entity_id', 'in', ns.mobile_app_sensors) %}

          {% for sensor in sensors %}
            {% if sensor.state | int(-1) < 10 %}
              {% set ns.entities = ns.entities + [sensor] %}
            {% endif %}
          {% endfor %}

          {{ ns.entities | count }}
        icon_template: '{{ is_state("sensor.low_battery_devices", "0") | iif("mdi:battery", "mdi:battery-alert") }}'
        attribute_templates:
          entities: >-
            {% set ns = namespace(entities=[], mobile_app_sensors=[]) %}
            {%
              set sensors = states.sensor
                | selectattr('attributes.device_class', 'eq', 'battery')
                | rejectattr('state', 'in', ['unavailable', 'unknown'])
                | list
            %}

            {% for sensor in sensors %}
              {% if 'mobile_app' in device_attr(sensor.entity_id, 'identifiers') | map(attribute=0) %}
                {% set ns.mobile_app_sensors = ns.mobile_app_sensors + [sensor.entity_id] %}
              {% endif %}
            {% endfor %}
            {% set sensors = sensors | rejectattr('entity_id', 'in', ns.mobile_app_sensors) %}

            {% for sensor in sensors %}
              {% if sensor.state | int(-1) < 10 %}
                {% set ns.entities = ns.entities + [sensor] %}
              {% endif %}
            {% endfor %}

            {{ ns.entities | map(attribute='entity_id') | list }}

history:
  exclude:
    entities:
      - 'sensor.low_battery'

automation:
  - alias: 'Low Battery'
    id: '685c0eb4-1d80-4ca3-8b5f-46a5e4e20c27'
    trigger:
      platform: 'state'
      entity_id: 'sensor.low_battery'
    action:
      if:
        condition: 'numeric_state'
        entity_id: 'sensor.low_battery'
        below: 1
      then:
        service: 'script.mobile_app_clear_notification'
        data:
          target: 'josh_phone'
          tag: 'low-battery'
      else:
        service: 'script.mobile_app_notify'
        data:
          target: 'josh_phone'
          title: 'Low Battery'
          message: >-
            {{ states('sensor.low_battery') }} devices with low battery.

            {% for entity in state_attr('sensor.low_battery', 'entities') -%}
            - {{ entity }}
            {% endfor %}
          tag: 'low-battery'
    mode: 'restart'
