---
mqtt:
  broker: 'core-mosquitto'
  username: 'homeassistant'
  password: !secret 'mqtt.password'

sensor:
  - platform: 'mqtt'
    state_topic: 'zigbee2mqtt/bridge/state'
    name: 'Zigbee2MQTT State'
    unique_id: '0e78cda4-e06a-4174-a663-1badfc31f315'
