---
mqtt:
  broker: 'core-mosquitto'
  username: 'homeassistant'
  password: !secret 'mqtt.password'

sensor:
  - platform: 'mqtt'
    name: 'Zigbee2MQTT Network Map'
    unique_id: 'f6ec75b3-c952-4c8f-9a62-a07f0eb063b2'
    state_topic: 'zigbee2mqtt/bridge/response/networkmap'
    value_template: '{{ now().strftime("%Y-%m-%d %H:%M:%S") }}'
    json_attributes_topic: 'zigbee2mqtt/bridge/response/networkmap'
    json_attributes_template: '{{ value_json.data.value | tojson }}'
  - platform: 'mqtt'
    state_topic: 'zigbee2mqtt/bridge/state'
    name: 'Zigbee2MQTT State'
    unique_id: '0e78cda4-e06a-4174-a663-1badfc31f315'

automation:
  - alias: 'Zigbee2MQTT Network Map'
    id: '2b67c904-fb8f-41d3-983d-a013f7c510ba'
    trigger:
      - platform: 'homeassistant'
        event: 'start'
      - platform: 'time_pattern'
        hours: '*'
    action:
      service: 'mqtt.publish'
      data:
        topic: 'zigbee2mqtt/bridge/request/networkmap'
        payload: 'raw'
