---
netgear_lte:
  - host: '192.168.200.1'
    password: !secret 'netgear_lte.password'
    notify:
      - name: 'sms_josh'
        recipient: !secret 'phone_number.josh'
      - name: 'sms_lily'
        recipient: !secret 'phone_number.lily'
    sensor:
      monitored_conditions:
        - 'radio_quality'
        - 'sms'
        - 'sms_total'
        - 'usage'

        # TODO: Are these useful?
        - 'cell_id'
        - 'connection_text'
        - 'connection_type'
        - 'current_band'
        - 'current_ps_service_type'
        - 'register_network_display'
        - 'rx_level'
        - 'tx_level'
        - 'upstream'
    binary_sensor:
      monitored_conditions:
        - 'mobile_connected'
        - 'roaming'

        # TODO: Are these useful?
        - 'wire_connected'

# http://192.168.200.1/index.html#messaging/1
automation:
  - id: '595cc2f2-ac5d-4447-a995-5d6e71327141'
    alias: 'Netgear SMS'
    trigger:
      platform: 'event'
      event_type: 'netgear_lte_sms'
    action:
      # TODO: Call `netgear_lte.delete_sms`.
      - service: 'script.mobile_app_notify'
        data:
          target: 'josh_phone'
          title: 'SMS Message Received - {{ trigger.event.data.from }}'
          message: '{{ trigger.event.data.message }}'
