---
automation:
  - id: '595cc2f2-ac5d-4447-a995-5d6e71327141'
    alias: 'Netgear SMS'
    triggers:
      - trigger: 'event'
        event_type: 'netgear_lte_sms'
        id: 'receive'
      - trigger: 'event'
        event_type: 'mobile_app_notification_action'
        event_data:
          action: 'netgear_lte.delete_sms'
        id: 'delete'
    actions:
      choose:
        - conditions:
            condition: 'trigger'
            id: 'receive'
          sequence:
            action: 'script.mobile_app_notify'
            data:
              target: 'josh_phone'
              title: 'SMS Message Received'
              subtitle: '{{ trigger.event.data.from }}'
              message: '{{ trigger.event.data.message }}'
              actions:
                - action: 'URI'
                  title: 'Open'
                  uri: 'http://{{ trigger.event.data.host }}#messaging/{{ trigger.event.data.sms_id }}'
                - action: 'netgear_lte.delete_sms'
                  title: 'Delete'
                  uri: '{{ trigger.event.data.sms_id }}'
              channel: 'Netgear LTE SMS'
              group: 'netgear_lte'
              icon: 'mdi:message-text'
        - conditions:
            condition: 'trigger'
            id: 'delete'
          sequence:
            action: 'netgear_lte.delete_sms'
            data:
              sms_id: '{{ trigger.event.data.action_2_uri }}'
