---
netgear_lte:
  - host: '192.168.5.1'
    password: !secret 'netgear_lte.password'
    notify:
      - name: 'sms_josh'
        recipient: !secret 'phone_number.josh'
      - name: 'sms_lily'
        recipient: !secret 'phone_number.lily'
    sensor:
      monitored_conditions:
        - 'sms'
        - 'usage'
    binary_sensor:
      monitored_conditions:
        - 'mobile_connected'
        - 'roaming'
        - 'wire_connected'

automation:
  - id: '595cc2f2-ac5d-4447-a995-5d6e71327141'
    alias: 'Netgear SMS'
    trigger:
      platform: 'event'
      event_type: 'netgear_lte_sms'
    action:
      # TODO: Call `netgear_lte.delete_sms`.
      - service: 'notify.mobile_app_josh_phone'
        data:
          title: 'SMS Message Received - {{ trigger.event.data.from }}'
          message: '{{ trigger.event.data.message }}'
