---
history:
  exclude:
    domains:
      - 'automation'
    entities:
      - 'binary_sensor.remote_ui'
      - 'sensor.backup_state'
      - 'sensor.snapshot_backup'
    entity_globs:
      - 'sensor.*_shelly*_temperature'
      - 'sensor.*_version'
      - 'sensor.speedtest_*'

logbook:
  exclude:
    entity_globs: []

recorder:
  auto_purge: false
  purge_keep_days: 30
  commit_interval: 300
  exclude:
    domains: []
    entities: []
    entity_globs: []
    event_types: []

automation:
  - id: '09c4eacb-3c9c-4e2a-84f1-a1a5d84e71ee'
    alias: 'Recorder Purge'
    trigger:
      platform: 'time'
      at: '04:12'
    action:
      service: 'recorder.purge'

  - id: '28f8f02d-010a-484a-aca3-35e27f43352d'
    alias: 'Recorder Repack'
    trigger:
      platform: 'time'
      at: '05:00'
    condition:
      condition: 'time'
      weekday:
        - 'sun'
    action:
      service: 'recorder.purge'
      data:
        repack: true

sensor:
  - platform: 'sql'
    queries:
      - name: 'Recorder Size'
        query: 'SELECT page_count * page_size AS size FROM pragma_page_count(), pragma_page_size()'
        column: 'size'
        unit_of_measurement: 'MiB'
        value_template: '{{ ((value | int) / (1024 * 1024)) | round }}'
      - name: 'Recorder Events'
        query: 'SELECT COUNT(*) AS count FROM events'
        column: 'count'
      - name: 'Recorder States'
        query: 'SELECT COUNT(*) AS count FROM states'
        column: 'count'
    scan_interval: 600
