---
# Workaround for home-assistant/core#62172.
automation:
  - alias: 'Speedtest Unavailable'
    id: 'c142089f-4826-4de4-b813-c188885e874f'
    trigger:
      platform: 'state'
      entity_id: &entity_id
        - 'sensor.speedtest_download'
        - 'sensor.speedtest_ping'
        - 'sensor.speedtest_upload'
      to: &state 'unavailable'
    condition:
      condition: 'state'
      entity_id: *entity_id
      state: *state
    action:
      - service: 'system_log.write'
        data:
          message: 'Speedtest entities are unavailable, calling "speedtestdotnet.speedtest".'
          level: 'warning'
      - service: 'speedtestdotnet.speedtest'
    mode: 'restart'
