---
sensor:
  - platform: 'min_max'
    entity_ids:
      - 'sensor.dining_room_humidity'
      - 'sensor.kitchen_humidity'
      - 'sensor.living_room_humidity'
    type: 'mean'
    name: 'Downstairs Humidity'
  - platform: 'min_max'
    entity_ids:
      - 'sensor.dining_room_temperature'
      - 'sensor.kitchen_temperature'
      - 'sensor.living_room_temperature'
    type: 'mean'
    name: 'Downstairs Temperature'

  - platform: 'min_max'
    entity_ids:
      - 'sensor.bedroom_1_humidity'
      - 'sensor.bedroom_2_humidity'
      - 'sensor.hallway_humidity'
      - 'sensor.office_humidity'
    type: 'mean'
    name: 'Upstairs Humidity'
  - platform: 'min_max'
    entity_ids:
      - 'sensor.bedroom_1_temperature'
      - 'sensor.bedroom_2_temperature'
      - 'sensor.hallway_temperature'
      - 'sensor.office_temperature'
    type: 'mean'
    name: 'Upstairs Temperature'

  - platform: 'min_max'
    entity_ids:
      - 'sensor.bedroom_1_humidity'
      - 'sensor.bedroom_2_humidity'
      - 'sensor.dining_room_humidity'
      - 'sensor.hallway_humidity'
      - 'sensor.kitchen_humidity'
      - 'sensor.living_room_humidity'
      - 'sensor.office_humidity'
    type: 'mean'
    name: 'Inside Humidity'
  - platform: 'min_max'
    entity_ids:
      - 'sensor.bedroom_1_temperature'
      - 'sensor.bedroom_2_temperature'
      - 'sensor.dining_room_temperature'
      - 'sensor.hallway_temperature'
      - 'sensor.kitchen_temperature'
      - 'sensor.living_room_temperature'
      - 'sensor.office_temperature'
    type: 'mean'
    name: 'Inside Temperature'

  - platform: 'min_max'
    entity_ids:
      - 'sensor.outside_north_humidity'
      - 'sensor.outside_south_humidity'
    type: 'mean'
    name: 'Outside Humidity'
  - platform: 'min_max'
    entity_ids:
      - 'sensor.outside_north_temperature'
      - 'sensor.outside_south_temperature'
    type: 'mean'
    name: 'Outside Temperature'

  - platform: 'min_max'
    entity_ids:
      - 'sensor.attic_lower_humidity'
      - 'sensor.attic_upper_humidity'
    type: 'mean'
    name: 'Attic Humidity'
  - platform: 'min_max'
    entity_ids:
      - 'sensor.attic_lower_temperature'
      - 'sensor.attic_upper_temperature'
    type: 'mean'
    name: 'Attic Temperature'

  - platform: 'min_max'
    entity_ids:
      - 'sensor.basement_east_humidity'
      - 'sensor.basement_west_humidity'
    type: 'mean'
    name: 'Basement Humidity'
  - platform: 'min_max'
    entity_ids:
      - 'sensor.basement_east_temperature'
      - 'sensor.basement_west_temperature'
    type: 'mean'
    name: 'Basement Temperature'

  # TODO: Set `calibration_factor` correctly.
  - platform: 'mold_indicator'
    name: 'Basement Mould Indicator'
    indoor_temp_sensor: 'sensor.basement_temperature'
    indoor_humidity_sensor: 'sensor.basement_humidity'
    outdoor_temp_sensor: 'sensor.outside_temperature'
    calibration_factor: 0.75

# Temporary sensor to calculate `calibration_factor` for `sensor.basement_mould_indicator`.
template:
  - trigger:
      platform: 'state'
      entity_id:
        - 'sensor.basement_temperature'
        - 'sensor.outside_temperature'
    sensor:
      - name: 'Basement Mould Indicator Calibration Factor'
        unique_id: 'f0db2ef6-0f97-4268-872a-a44894bb9294'
        state: '{{ (states("sensor.basement_temperature")|float - states("sensor.outside_temperature")|float) / (states("sensor.basement_west_temperature")|float - states("sensor.outside_temperature")|float) }}'
        unit_of_measurement: '%'
