---
sensor:
  - platform: 'systemmonitor'
    resources:
      - type: 'disk_use_percent'
      - type: 'last_boot'
      - type: 'memory_use_percent'
      - type: 'processor_temperature'
      - type: 'processor_use'
system_log: {}

homeassistant:
  customize:
    sensor.disk_use_percent:
      friendly_name: 'Disk use'
    sensor.memory_use_percent:
      friendly_name: 'Memory use'
    sensor.processor_temperature:
      icon: 'mdi:thermometer'
    sensor.processor_use_percent:
      friendly_name: 'Processor use'
