---
sensor:
  - platform: 'systemmonitor'
    resources:
      - type: 'disk_free'
      - type: 'disk_use'
      - type: 'disk_use_percent'
      - type: 'memory_free'
      - type: 'memory_use'
      - type: 'memory_use_percent'
      - type: 'processor_temperature'
      - type: 'processor_use'
system_health: {}
system_log: {}
