---
localtuya:
  - host: &attic_ridge_host '192.168.20.12'
    device_id: !secret 'tuya.attic_ridge.device_id'
    local_key: !secret 'tuya.attic_ridge.local_key'
    friendly_name: 'Attic Ridge Light Strip'
    scan_interval: 120
    entities:
      - platform: 'light'
        friendly_name: 'Attic Ridge'
        color: 24
        <<: &common_config
          id: 20
          color_mode: 21
          brightness: 22
          color_temp: 23

  - host: &attic_1_host '192.168.20.16'
    device_id: !secret 'tuya.attic_1.device_id'
    local_key: !secret 'tuya.attic_1.local_key'
    friendly_name: 'Attic Light Strip 1'
    scan_interval: 120
    entities:
      - platform: 'light'
        friendly_name: 'Attic 1'
        <<: *common_config

  - host: &attic_2_host '192.168.20.17'
    device_id: !secret 'tuya.attic_2.device_id'
    local_key: !secret 'tuya.attic_2.local_key'
    friendly_name: 'Attic Light Strip 2'
    scan_interval: 120
    entities:
      - platform: 'light'
        friendly_name: 'Attic 2'
        <<: *common_config

  - host: &attic_3_host '192.168.20.18'
    device_id: !secret 'tuya.attic_3.device_id'
    local_key: !secret 'tuya.attic_3.local_key'
    friendly_name: 'Attic Light Strip 3'
    scan_interval: 120
    entities:
      - platform: 'light'
        friendly_name: 'Attic 3'
        <<: *common_config

  - host: &bedroom_1_ceiling_projector_host '192.168.20.49'
    device_id: !secret 'tuya.bedroom_1_ceiling_projector.device_id'
    local_key: !secret 'tuya.bedroom_1_ceiling_projector.local_key'
    friendly_name: 'Bedroom 1 Ceiling Projector'
    scan_interval: 120
    entities:
      - platform: 'switch'
        friendly_name: 'Bedroom 1 Ceiling Projector'
        id: 20

      - platform: 'light'
        friendly_name: 'Bedroom 1 Ceiling Projector Light'
        id: 52
        color: 24
        color_mode: 51

      - platform: 'light'
        friendly_name: 'Bedroom 1 Ceiling Projector Laser'
        id: 53
        brightness: 54
        brightness_lower: 10

      - platform: 'light'
        friendly_name: 'Bedroom 1 Ceiling Projector Motor'
        id: 60
        brightness: 62
        brightness_lower: 0
        brightness_upper: 100

automation:
  # Workaround for rospogrigio/localtuya#699.
  - id: '20f77719-a3f1-4c2b-9bbf-9574b16e9167'
    alias: 'Mirabella Genio Star Project color_mode Fix'
    trigger:
      platform: 'event'
      event_type: 'call_service'
      event_data:
        domain: 'light'
        service: 'turn_on'
        service_data:
          entity_id: 'light.bedroom_1_ceiling_projector_light'
    action:
      service: 'localtuya.set_dp'
      data:
        device_id: !secret 'tuya.bedroom_1_ceiling_projector.device_id'
        dp: 51
        value: 'manual'
    max_exceeded: 'silent'
