---
# TODO: Don't hardcode IP addresses (see rospogrigio/localtuya#741).
localtuya:
  - host: '192.168.20.12'
    device_id: !secret 'localtuya.attic_ridge.device_id'
    local_key: !secret 'localtuya.attic_ridge.local_key'
    friendly_name: 'Attic Ridge Light Strip'
    scan_interval: 120
    entities:
      - platform: 'light'
        friendly_name: 'Attic Ridge'
        color: 24
        <<: &common_config
          id: 20
          color_mode: 21
          brightness: 22
          color_temp: 23

  - host: '192.168.20.16'
    device_id: !secret 'localtuya.attic_1.device_id'
    local_key: !secret 'localtuya.attic_1.local_key'
    friendly_name: 'Attic Light Strip 1'
    scan_interval: 120
    entities:
      - platform: 'light'
        friendly_name: 'Attic 1'
        <<: *common_config

  - host: '192.168.20.17'
    device_id: !secret 'localtuya.attic_2.device_id'
    local_key: !secret 'localtuya.attic_2.local_key'
    friendly_name: 'Attic Light Strip 2'
    scan_interval: 120
    entities:
      - platform: 'light'
        friendly_name: 'Attic 2'
        <<: *common_config

  - host: '192.168.20.18'
    device_id: !secret 'localtuya.attic_3.device_id'
    local_key: !secret 'localtuya.attic_3.local_key'
    friendly_name: 'Attic Light Strip 3'
    scan_interval: 120
    entities:
      - platform: 'light'
        friendly_name: 'Attic 3'
        <<: *common_config

  - host: '192.168.10.145'
    device_id: !secret 'localtuya.bedroom_1_air_purifier.device_id'
    local_key: !secret 'localtuya.bedroom_1_air_purifier.local_key'
    friendly_name: 'Bedroom 1 Air Purifier'
    scan_interval: 120
    entities:
      - platform: 'fan'
        friendly_name: 'Bedroom 1 Air Purifier'
        id: 1
        fan_speed_control: 4
        fan_speed_ordered_list: 'low,mid,high,turbo'
      - platform: 'sensor'
        friendly_name: 'Bedroom 1 Particulate Matter'
        id: 2
        device_class: 'pm25'
        unit_of_measurement: 'μg/m³'
        scaling: 0.1
      - platform: 'select'
        friendly_name: 'Bedroom 1 Air Purifier Mode'
        id: 3
        select_options: 'manual;auto'
        select_options_friendly: 'Manual;Auto'
      - platform: 'switch'
        friendly_name: 'Bedroom 1 Air Purifier Night Mode'
        id: 8
      - platform: 'switch'
        friendly_name: 'Bedroom 1 Air Purifier UV Sterilization'
        id: 9
      - platform: 'switch'
        friendly_name: 'Bedroom 1 Air Purifier Filter Reset'
        id: 11
      - platform: 'sensor'
        friendly_name: 'Bedroom 1 Air Purifier Filter Remaining Time'
        id: 16
        unit_of_measurement: 'days'

homeassistant:
  customize:
    sensor.bedroom_1_air_purifier_filter_remaining_time:
      icon: 'mdi:calendar-clock'
    switch.bedroom_1_air_purifier_uv_sterilization:
      icon: 'mdi:minus-circle-outline'
