---
localtuya:
  - host: '192.168.20.12'
    device_id: !secret 'localtuya.attic_ridge.device_id'
    local_key: !secret 'localtuya.attic_ridge.local_key'
    friendly_name: 'Attic Ridge Light Strip'
    scan_interval: 120
    entities:
      - platform: 'light'
        friendly_name: 'Attic Ridge'
        color: 24
        <<: &common_config
          id: 20
          color_mode: 21
          brightness: 22
          color_temp: 23

  - host: '192.168.20.16'
    device_id: !secret 'localtuya.attic_1.device_id'
    local_key: !secret 'localtuya.attic_1.local_key'
    friendly_name: 'Attic Light Strip 1'
    scan_interval: 120
    entities:
      - platform: 'light'
        friendly_name: 'Attic 1'
        <<: *common_config

  - host: '192.168.20.17'
    device_id: !secret 'localtuya.attic_2.device_id'
    local_key: !secret 'localtuya.attic_2.local_key'
    friendly_name: 'Attic Light Strip 2'
    scan_interval: 120
    entities:
      - platform: 'light'
        friendly_name: 'Attic 2'
        <<: *common_config

  - host: '192.168.20.18'
    device_id: !secret 'localtuya.attic_3.device_id'
    local_key: !secret 'localtuya.attic_3.local_key'
    friendly_name: 'Attic Light Strip 3'
    scan_interval: 120
    entities:
      - platform: 'light'
        friendly_name: 'Attic 3'
        <<: *common_config

  - host: '192.168.10.145'
    device_id: !secret 'localtuya.bedroom_1_air_purifier.device_id'
    local_key: !secret 'localtuya.bedroom_1_air_purifier.local_key'
    friendly_name: 'Bedroom 1 Air Purifier'
    scan_interval: 120
    entities:
      - platform: 'fan'
        friendly_name: 'Bedroom 1 Air Purifier'
        id: 1
        fan_speed_control: 4
        fan_speed_ordered_list: 'low,mid,high,turbo'
      - platform: 'sensor'
        friendly_name: 'Bedroom 1 Air Quality'
        id: 2
        device_class: 'pm25'
        unit_of_measurement: 'μg/m³'
        scaling: 0.1
      - platform: 'select'
        friendly_name: 'Bedroom 1 Air Purifier Mode'
        id: 3
        select_options: 'manual;auto'
        select_options_friendly: 'Manual;Auto'
      - platform: 'switch'
        friendly_name: 'Bedroom 1 Air Purifier Night Mode'
        id: 8
      - platform: 'switch'
        friendly_name: 'Bedroom 1 Air Purifier Microbe Shield'
        id: 9
      - platform: 'sensor'
        friendly_name: 'Bedroom 1 Air Purifier Filter Remaining Time'
        id: 16
        unit_of_measurement: 'days'

  - host: '192.168.20.49'
    device_id: !secret 'localtuya.bedroom_1_ceiling_projector.device_id'
    local_key: !secret 'localtuya.bedroom_1_ceiling_projector.local_key'
    friendly_name: 'Bedroom 1 Ceiling Projector'
    scan_interval: 120
    entities:
      - platform: 'switch'
        friendly_name: 'Bedroom 1 Ceiling Projector'
        id: 20
      - platform: 'light'
        friendly_name: 'Bedroom 1 Ceiling Projector Light'
        id: 52
        color: 24
        color_mode: 51
      - platform: 'light'
        friendly_name: 'Bedroom 1 Ceiling Projector Laser'
        id: 53
        brightness: 54
        brightness_lower: 10
      - platform: 'light'
        friendly_name: 'Bedroom 1 Ceiling Projector Motor'
        id: 60
        brightness: 62
        brightness_lower: 0
        brightness_upper: 100

automation:
  # Workaround for rospogrigio/localtuya#699.
  - id: '20f77719-a3f1-4c2b-9bbf-9574b16e9167'
    alias: 'Mirabella Genio Star Project color_mode Fix'
    trigger:
      platform: 'event'
      event_type: 'call_service'
      event_data:
        domain: 'light'
        service: 'turn_on'
        service_data:
          entity_id: 'light.bedroom_1_ceiling_projector_light'
    action:
      service: 'localtuya.set_dp'
      data:
        device_id: !secret 'localtuya.bedroom_1_ceiling_projector.device_id'
        dp: 51
        value: 'manual'
    max_exceeded: 'silent'
    trace:
      stored_traces: 0
