---
sensor:
  - platform: 'unifigateway'
    host: 'localhost'
    port: 8443
    username: !secret 'unifi.username'
    password: !secret 'unifi.password'

automation:
  - alias: 'Unifi Alerts'
    id: 'e1448032-b0ca-4b23-a8b1-2c044e441426'
    trigger:
      platform: 'state'
      entity_id: 'sensor.unifi_gateway_alerts'
    action:
      choose:
        conditions:
          condition: 'numeric_state'
          entity_id: 'sensor.unifi_gateway_alerts'
          below: 1
        sequence:
          service: 'notify.mobile_app_josh_phone'
          data:
            message: 'clear_notification'
            data:
              tag: 'unifi-alert'
      default:
        service: 'notify.mobile_app_josh_phone'
        data:
          title: 'Unifi Alerts'
          message: >-
            There are {{ trigger.to_state.state }} gateway alerts.

            {% for key, value in trigger.to_state.attributes.items() -%}
            {%   if key | int(-1) != -1 -%}
            - {{ value.msg }}
            {%   endif -%}
            {% endfor %}
          data:
            tag: 'unifi-alert'
    mode: 'restart'

  - alias: 'Unifi Firmware Updates Available'
    id: '4dbd094b-c008-4625-b3b6-7b336954b103'
    trigger:
      platform: 'state'
      entity_id: 'sensor.unifi_gateway_firmware_upgradable'
    action:
      choose:
        conditions:
          condition: 'numeric_state'
          entity_id: 'sensor.unifi_gateway_firmware_upgradable'
          below: 1
        sequence:
          service: 'persistent_notification.dismiss'
          data:
            notification_id: 'unifi-firmware'
      default:
        service: 'persistent_notification.create'
        data:
          title: 'Unifi Firmware Updates Available'
          message: 'There are {{ trigger.to_state.state }} firmware updates available.'
          notification_id: 'unifi-firmware'
    mode: 'restart'
