---
# NOTE: I am using [`hacc-ozmo`](https://github.com/Ligio/hacc-ozmo) rather than
# the [official integration](https://www.home-assistant.io/integrations/ecovacs).
# See https://github.com/home-assistant/core/issues/38625 for some additional context.
deebot:
  continent: 'WW'
  country: 'AU'
  password: !secret 'ecovacs.password'
  username: !secret 'ecovacs.username'

automation:
  - alias: 'Vacuum Error'
    id: '10a065f5-f820-42d7-aa54-ceae3e8a4993'
    trigger:
      platform: 'state'
      entity_id: &entity_id 'vacuum.deebot'
      attribute: &error_attribute 'error'
    condition:
      condition: 'not'
      conditions:
        condition: 'state'
        entity_id: *entity_id
        attribute: *error_attribute
        state:
          - null
          - 'low_battery'
    action:
      service: 'notify.mobile_app_josh_phone'
      data:
        title: 'Vacuum {{ trigger.to_state.friendly_name }} has experienced an error'
        message: >
          {%
            set error_messages = {
              'host_hang': 'The robot is off the floor.',
              'no_dust_box': 'Dust Bin not installed.',
              'wheel_abnormal': 'Operating difficulties encountered. Please check the Driving Wheel.',
            }
          %}
          {% set error_code = trigger.to_state.attributes.error %}
          {{ error_messages[error_code] if error_code in error_messages else 'An unknown error occurred (' ~ error_code ~ ').' }}
  - alias: 'Vacuum Low Battery'
    id: '77a8cf42-1126-4741-be4a-17869fadcabb'
    trigger:
      platform: 'numeric_state'
      entity_id: *entity_id
      attribute: 'battery_level'
      below: 20
    condition:
      condition: 'not'
      conditions:
        - condition: 'state'
          entity_id: *entity_id
          attribute: 'status'
          state: 'charging'
        - condition: 'state'
          entity_id: *entity_id
          state: 'returning'
    action:
      service: 'vacuum.return_to_base'
      data:
        entity_id: *entity_id
  - alias: 'Start vacuum'
    id: '01119384-ba58-4ae6-8cfc-1c32708691ba'
    trigger:
      - platform: 'state'
        entity_id: 'group.family'
        to: 'home'
      - platform: 'time'
        at: '13:00'
    action:
      service: 'vacuum.start'
      entity_id: *entity_id
    mode: 'single'
  - id: '46e2e798-2a9d-4d8c-aa73-bb989ac33099'
    alias: 'Vacuum Stuck'
    trigger:
      platform: 'state'
      entity_id: *entity_id
      attribute: 'status'
      to: 'returning'
      for:
        minutes: 30
    action:
      service: 'notify.mobile_app_josh_phone'
      data:
        title: 'Vacuum Stuck'
        message: 'Vaccum has been returning to base for 30 minutes and is likely stuck.'
