---
met: {}
sun: {}

homeassistant:
  customize:
    weather.home:
      friendly_name: 'Weather'
    weather.home_hourly:
      friendly_name: 'Weather (Hourly)'
recorder:
  exclude:
    domains:
      - 'sun'
      - 'weather'
