---
binary_sensor:
  - platform: 'workday'
    name: 'Workday'
    country: 'AU'
    province: 'NSW'

automation:
  - alias: 'Workday Lighting'
    id: '11806cb8-d600-48be-a74a-ac71bf258626'
    trigger:
      - platform: 'time'
        at: '08:30'
        variables:
          scene:
            light.office:
              brightness: 255
              state: 'on'
      - platform: 'time'
        at: '18:00'
        variables:
          scene:
            light.office:
              state: 'off'
    condition:
      condition: 'state'
      entity_id: 'binary_sensor.workday'
      state: 'on'
    action:
      service: 'scene.apply'
      data:
        entities: '{{ scene }}'

history:
  exclude:
    entities:
      - 'binary_sensor.workday'
