---
name: 'Lint'
on:
  pull_request: {}
  push: {}
jobs:
  eslint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'actions/setup-node@v2'
        with:
          node-version: '14'
      - run: 'npm install eslint eslint-config-airbnb-base eslint-plugin-import'
      - run: 'npx eslint zigbee2mqtt'
  yamllint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'ibiqlik/action-yamllint@v3'
