---
name: 'Lint'
on:
  pull_request: {}
  push: {}
jobs:
  eslint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'actions/setup-node@v2'
        with:
          node-version: '14'
      - run: 'npm install --global eslint eslint-config-google'
      - run: 'eslint --resolve-plugins-relative-to $(npm root --global) zigbee2mqtt'
  yamllint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'ibiqlik/action-yamllint@v3'
