---
name: 'Lint'
on:
  pull_request: {}
  push:
    branches:
      - 'master'
jobs:
  eslint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'
      - uses: 'actions/setup-node@v3'
        with:
          node-version: 'latest'
      - run: 'npx --package eslint --package eslint-config-airbnb-base --package eslint-plugin-import eslint zigbee2mqtt/'
  yamllint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'
      - uses: 'ibiqlik/action-yamllint@v3'
