---
name: 'Lint'
on:
  pull_request: {}
  push:
    branches:
      - 'master'
jobs:
  eslint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'actions/setup-node@v3'
        with:
          node-version: 'latest'
      - run: 'npm install eslint eslint-config-airbnb-base eslint-plugin-eslint-comments eslint-plugin-import'
      - run: 'npx eslint zigbee2mqtt/'
  yamllint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'ibiqlik/action-yamllint@v3'
