---
name: 'Lint'
on:
  pull_request: {}
  push: {}
jobs:
  markdownlint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'avto-dev/markdown-lint@v1'
        with:
          args: '.'
  yamllint:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'ibiqlik/action-yamllint@v3'
