---
name: 'Test'
on:
  pull_request: {}
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 0 * * *'
jobs:
  esphome:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        version:
          - 'dev'
          - 'beta'
          - 'latest'
    continue-on-error: '${{ matrix.version != ''latest'' }}'
    container:
      image: 'esphome/esphome:${{ matrix.version }}'
    steps:
      - uses: 'actions/checkout@v5'
      - uses: 'canastro/copy-action@0.0.2'
        with:
          source: '.github/stubs/esphome_secrets.yaml'
          target: 'esphome/secrets.yaml'
      - run: 'esphome config esphome/*.yaml'

  home-assistant:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        version:
          - 'dev'
          - 'beta'
          - 'stable'
    continue-on-error: '${{ matrix.version != ''stable'' }}'
    steps:
      - uses: 'actions/checkout@v5'
      - uses: 'frenck/action-home-assistant@v1.4'
        with:
          secrets: '.github/stubs/hass_secrets.yaml'
          version: '${{ matrix.version }}'
