---
name: 'Test'
on: 'push'
jobs:
  home-assistant:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'canastro/copy-action@0.0.2'
        with:
          source: '.github/stubs/secrets.yaml'
          target: '.'

      # TODO: Consider using
      # https://github.com/marketplace/actions/home-assistant-configuration-check.
      - uses: 'docker://homeassistant/home-assistant:stable'
        with:
          args: 'python -m homeassistant --config . --script check_config'
