---
name: 'Test'
on: 'push'
jobs:
  home-assistant:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'docker://homeassistant/home-assistant:stable'
        with:
          args: |
            python -m homeassistant --config . --script check_config --info all
