---
name: 'Test'
on:
  pull_request: {}
  push: {}
  schedule:
    - cron: '0 0 * * *'
jobs:
  home-assistant:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'frenck/action-home-assistant@v1'
        with:
          secrets: '.github/stubs/secrets.yaml'
          version: '${{ matrix.version }}'
    strategy:
      matrix:
        version:
          - 'beta'
          - 'stable'
