---
name: 'Test'
on:
  pull_request: {}
  push: {}
  schedule:
    - cron: '0 0 * * *'
jobs:
  esphome:
    runs-on: 'ubuntu-latest'
    container:
      image: 'esphome/esphome:latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'canastro/copy-action@0.0.2'
        with:
          source: '.github/stubs/esphome_secrets.yaml'
          target: 'esphome/secrets.yaml'
      - run: 'find esphome -maxdepth 1 -type f -name "*.yaml" -not -name secrets.yaml -exec esphome config {} \;'

  home-assistant:
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        version:
          - 'beta'
          - 'stable'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'frenck/action-home-assistant@v1'
        with:
          secrets: '.github/stubs/hass_secrets.yaml'
          version: '${{ matrix.version }}'
