---
name: 'Test'
on: 'push'
jobs:
  home-assistant:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'
      - uses: 'DamianReeves/write-file-action@v1.0'
        with:
          path: 'secrets.yaml'
          contents: |
            ---
            latitude: 0
            longitude: 0
      - uses: 'docker://homeassistant/home-assistant:stable'
        with:
          args: 'python -m homeassistant --config . --script check_config'
